
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model State
 * 
 */
export type State = Prisma.StateModel
/**
 * Model District
 * 
 */
export type District = Prisma.DistrictModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model CulturalStory
 * 
 */
export type CulturalStory = Prisma.CulturalStoryModel
/**
 * Model CartItem
 * 
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model WishlistItem
 * 
 */
export type WishlistItem = Prisma.WishlistItemModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
/**
 * Model Coupon
 * 
 */
export type Coupon = Prisma.CouponModel
/**
 * Model Banner
 * 
 */
export type Banner = Prisma.BannerModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model BlogPost
 * 
 */
export type BlogPost = Prisma.BlogPostModel
/**
 * Model Vendor
 * 
 */
export type Vendor = Prisma.VendorModel
/**
 * Model VendorDocument
 * 
 */
export type VendorDocument = Prisma.VendorDocumentModel
/**
 * Model VendorBankAccount
 * 
 */
export type VendorBankAccount = Prisma.VendorBankAccountModel
/**
 * Model ApprovalWorkflow
 * 
 */
export type ApprovalWorkflow = Prisma.ApprovalWorkflowModel
/**
 * Model WorkflowComment
 * 
 */
export type WorkflowComment = Prisma.WorkflowCommentModel
/**
 * Model ProductStatusHistory
 * 
 */
export type ProductStatusHistory = Prisma.ProductStatusHistoryModel
/**
 * Model Payout
 * 
 */
export type Payout = Prisma.PayoutModel
/**
 * Model StateMapAsset
 * 
 */
export type StateMapAsset = Prisma.StateMapAssetModel
/**
 * Model FooterSection
 * 
 */
export type FooterSection = Prisma.FooterSectionModel
/**
 * Model FooterLink
 * 
 */
export type FooterLink = Prisma.FooterLinkModel
/**
 * Model FooterSocialLink
 * 
 */
export type FooterSocialLink = Prisma.FooterSocialLinkModel
/**
 * Model FooterPaymentMethod
 * 
 */
export type FooterPaymentMethod = Prisma.FooterPaymentMethodModel
/**
 * Model FooterShippingPartner
 * 
 */
export type FooterShippingPartner = Prisma.FooterShippingPartnerModel
/**
 * Model FooterCertification
 * 
 */
export type FooterCertification = Prisma.FooterCertificationModel
/**
 * Model FooterContactInfo
 * 
 */
export type FooterContactInfo = Prisma.FooterContactInfoModel
/**
 * Model FooterLanguage
 * 
 */
export type FooterLanguage = Prisma.FooterLanguageModel
/**
 * Model FooterCurrency
 * 
 */
export type FooterCurrency = Prisma.FooterCurrencyModel
/**
 * Model FooterNewsletter
 * 
 */
export type FooterNewsletter = Prisma.FooterNewsletterModel
/**
 * Model FooterSettings
 * 
 */
export type FooterSettings = Prisma.FooterSettingsModel
