
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApprovalWorkflow` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApprovalWorkflow
 * 
 */
export type ApprovalWorkflowModel = runtime.Types.Result.DefaultSelection<Prisma.$ApprovalWorkflowPayload>

export type AggregateApprovalWorkflow = {
  _count: ApprovalWorkflowCountAggregateOutputType | null
  _min: ApprovalWorkflowMinAggregateOutputType | null
  _max: ApprovalWorkflowMaxAggregateOutputType | null
}

export type ApprovalWorkflowMinAggregateOutputType = {
  id: string | null
  productId: string | null
  currentStage: string | null
  assignedTo: string | null
  updatedAt: Date | null
}

export type ApprovalWorkflowMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  currentStage: string | null
  assignedTo: string | null
  updatedAt: Date | null
}

export type ApprovalWorkflowCountAggregateOutputType = {
  id: number
  productId: number
  currentStage: number
  assignedTo: number
  updatedAt: number
  _all: number
}


export type ApprovalWorkflowMinAggregateInputType = {
  id?: true
  productId?: true
  currentStage?: true
  assignedTo?: true
  updatedAt?: true
}

export type ApprovalWorkflowMaxAggregateInputType = {
  id?: true
  productId?: true
  currentStage?: true
  assignedTo?: true
  updatedAt?: true
}

export type ApprovalWorkflowCountAggregateInputType = {
  id?: true
  productId?: true
  currentStage?: true
  assignedTo?: true
  updatedAt?: true
  _all?: true
}

export type ApprovalWorkflowAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApprovalWorkflow to aggregate.
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalWorkflows to fetch.
   */
  orderBy?: Prisma.ApprovalWorkflowOrderByWithRelationInput | Prisma.ApprovalWorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApprovalWorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalWorkflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalWorkflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApprovalWorkflows
  **/
  _count?: true | ApprovalWorkflowCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApprovalWorkflowMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApprovalWorkflowMaxAggregateInputType
}

export type GetApprovalWorkflowAggregateType<T extends ApprovalWorkflowAggregateArgs> = {
      [P in keyof T & keyof AggregateApprovalWorkflow]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApprovalWorkflow[P]>
    : Prisma.GetScalarType<T[P], AggregateApprovalWorkflow[P]>
}




export type ApprovalWorkflowGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApprovalWorkflowWhereInput
  orderBy?: Prisma.ApprovalWorkflowOrderByWithAggregationInput | Prisma.ApprovalWorkflowOrderByWithAggregationInput[]
  by: Prisma.ApprovalWorkflowScalarFieldEnum[] | Prisma.ApprovalWorkflowScalarFieldEnum
  having?: Prisma.ApprovalWorkflowScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApprovalWorkflowCountAggregateInputType | true
  _min?: ApprovalWorkflowMinAggregateInputType
  _max?: ApprovalWorkflowMaxAggregateInputType
}

export type ApprovalWorkflowGroupByOutputType = {
  id: string
  productId: string
  currentStage: string
  assignedTo: string | null
  updatedAt: Date
  _count: ApprovalWorkflowCountAggregateOutputType | null
  _min: ApprovalWorkflowMinAggregateOutputType | null
  _max: ApprovalWorkflowMaxAggregateOutputType | null
}

export type GetApprovalWorkflowGroupByPayload<T extends ApprovalWorkflowGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApprovalWorkflowGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApprovalWorkflowGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApprovalWorkflowGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApprovalWorkflowGroupByOutputType[P]>
      }
    >
  >



export type ApprovalWorkflowWhereInput = {
  AND?: Prisma.ApprovalWorkflowWhereInput | Prisma.ApprovalWorkflowWhereInput[]
  OR?: Prisma.ApprovalWorkflowWhereInput[]
  NOT?: Prisma.ApprovalWorkflowWhereInput | Prisma.ApprovalWorkflowWhereInput[]
  id?: Prisma.StringFilter<"ApprovalWorkflow"> | string
  productId?: Prisma.StringFilter<"ApprovalWorkflow"> | string
  currentStage?: Prisma.StringFilter<"ApprovalWorkflow"> | string
  assignedTo?: Prisma.StringNullableFilter<"ApprovalWorkflow"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"ApprovalWorkflow"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  comments?: Prisma.WorkflowCommentListRelationFilter
}

export type ApprovalWorkflowOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  currentStage?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  comments?: Prisma.WorkflowCommentOrderByRelationAggregateInput
}

export type ApprovalWorkflowWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  productId?: string
  AND?: Prisma.ApprovalWorkflowWhereInput | Prisma.ApprovalWorkflowWhereInput[]
  OR?: Prisma.ApprovalWorkflowWhereInput[]
  NOT?: Prisma.ApprovalWorkflowWhereInput | Prisma.ApprovalWorkflowWhereInput[]
  currentStage?: Prisma.StringFilter<"ApprovalWorkflow"> | string
  assignedTo?: Prisma.StringNullableFilter<"ApprovalWorkflow"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"ApprovalWorkflow"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  comments?: Prisma.WorkflowCommentListRelationFilter
}, "id" | "productId">

export type ApprovalWorkflowOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  currentStage?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ApprovalWorkflowCountOrderByAggregateInput
  _max?: Prisma.ApprovalWorkflowMaxOrderByAggregateInput
  _min?: Prisma.ApprovalWorkflowMinOrderByAggregateInput
}

export type ApprovalWorkflowScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApprovalWorkflowScalarWhereWithAggregatesInput | Prisma.ApprovalWorkflowScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApprovalWorkflowScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApprovalWorkflowScalarWhereWithAggregatesInput | Prisma.ApprovalWorkflowScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ApprovalWorkflow"> | string
  productId?: Prisma.StringWithAggregatesFilter<"ApprovalWorkflow"> | string
  currentStage?: Prisma.StringWithAggregatesFilter<"ApprovalWorkflow"> | string
  assignedTo?: Prisma.StringNullableWithAggregatesFilter<"ApprovalWorkflow"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ApprovalWorkflow"> | Date | string
}

export type ApprovalWorkflowCreateInput = {
  id?: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutApprovalWorkflowInput
  comments?: Prisma.WorkflowCommentCreateNestedManyWithoutWorkflowInput
}

export type ApprovalWorkflowUncheckedCreateInput = {
  id?: string
  productId: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
  comments?: Prisma.WorkflowCommentUncheckedCreateNestedManyWithoutWorkflowInput
}

export type ApprovalWorkflowUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutApprovalWorkflowNestedInput
  comments?: Prisma.WorkflowCommentUpdateManyWithoutWorkflowNestedInput
}

export type ApprovalWorkflowUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comments?: Prisma.WorkflowCommentUncheckedUpdateManyWithoutWorkflowNestedInput
}

export type ApprovalWorkflowCreateManyInput = {
  id?: string
  productId: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
}

export type ApprovalWorkflowUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApprovalWorkflowUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApprovalWorkflowNullableScalarRelationFilter = {
  is?: Prisma.ApprovalWorkflowWhereInput | null
  isNot?: Prisma.ApprovalWorkflowWhereInput | null
}

export type ApprovalWorkflowCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  currentStage?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApprovalWorkflowMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  currentStage?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApprovalWorkflowMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  currentStage?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ApprovalWorkflowScalarRelationFilter = {
  is?: Prisma.ApprovalWorkflowWhereInput
  isNot?: Prisma.ApprovalWorkflowWhereInput
}

export type ApprovalWorkflowCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ApprovalWorkflowCreateOrConnectWithoutProductInput
  connect?: Prisma.ApprovalWorkflowWhereUniqueInput
}

export type ApprovalWorkflowUncheckedCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ApprovalWorkflowCreateOrConnectWithoutProductInput
  connect?: Prisma.ApprovalWorkflowWhereUniqueInput
}

export type ApprovalWorkflowUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ApprovalWorkflowCreateOrConnectWithoutProductInput
  upsert?: Prisma.ApprovalWorkflowUpsertWithoutProductInput
  disconnect?: Prisma.ApprovalWorkflowWhereInput | boolean
  delete?: Prisma.ApprovalWorkflowWhereInput | boolean
  connect?: Prisma.ApprovalWorkflowWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ApprovalWorkflowUpdateToOneWithWhereWithoutProductInput, Prisma.ApprovalWorkflowUpdateWithoutProductInput>, Prisma.ApprovalWorkflowUncheckedUpdateWithoutProductInput>
}

export type ApprovalWorkflowUncheckedUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ApprovalWorkflowCreateOrConnectWithoutProductInput
  upsert?: Prisma.ApprovalWorkflowUpsertWithoutProductInput
  disconnect?: Prisma.ApprovalWorkflowWhereInput | boolean
  delete?: Prisma.ApprovalWorkflowWhereInput | boolean
  connect?: Prisma.ApprovalWorkflowWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ApprovalWorkflowUpdateToOneWithWhereWithoutProductInput, Prisma.ApprovalWorkflowUpdateWithoutProductInput>, Prisma.ApprovalWorkflowUncheckedUpdateWithoutProductInput>
}

export type ApprovalWorkflowCreateNestedOneWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutCommentsInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.ApprovalWorkflowCreateOrConnectWithoutCommentsInput
  connect?: Prisma.ApprovalWorkflowWhereUniqueInput
}

export type ApprovalWorkflowUpdateOneRequiredWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutCommentsInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.ApprovalWorkflowCreateOrConnectWithoutCommentsInput
  upsert?: Prisma.ApprovalWorkflowUpsertWithoutCommentsInput
  connect?: Prisma.ApprovalWorkflowWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ApprovalWorkflowUpdateToOneWithWhereWithoutCommentsInput, Prisma.ApprovalWorkflowUpdateWithoutCommentsInput>, Prisma.ApprovalWorkflowUncheckedUpdateWithoutCommentsInput>
}

export type ApprovalWorkflowCreateWithoutProductInput = {
  id?: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
  comments?: Prisma.WorkflowCommentCreateNestedManyWithoutWorkflowInput
}

export type ApprovalWorkflowUncheckedCreateWithoutProductInput = {
  id?: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
  comments?: Prisma.WorkflowCommentUncheckedCreateNestedManyWithoutWorkflowInput
}

export type ApprovalWorkflowCreateOrConnectWithoutProductInput = {
  where: Prisma.ApprovalWorkflowWhereUniqueInput
  create: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutProductInput>
}

export type ApprovalWorkflowUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.ApprovalWorkflowUpdateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutProductInput>
  where?: Prisma.ApprovalWorkflowWhereInput
}

export type ApprovalWorkflowUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.ApprovalWorkflowWhereInput
  data: Prisma.XOR<Prisma.ApprovalWorkflowUpdateWithoutProductInput, Prisma.ApprovalWorkflowUncheckedUpdateWithoutProductInput>
}

export type ApprovalWorkflowUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comments?: Prisma.WorkflowCommentUpdateManyWithoutWorkflowNestedInput
}

export type ApprovalWorkflowUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comments?: Prisma.WorkflowCommentUncheckedUpdateManyWithoutWorkflowNestedInput
}

export type ApprovalWorkflowCreateWithoutCommentsInput = {
  id?: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutApprovalWorkflowInput
}

export type ApprovalWorkflowUncheckedCreateWithoutCommentsInput = {
  id?: string
  productId: string
  currentStage: string
  assignedTo?: string | null
  updatedAt?: Date | string
}

export type ApprovalWorkflowCreateOrConnectWithoutCommentsInput = {
  where: Prisma.ApprovalWorkflowWhereUniqueInput
  create: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutCommentsInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutCommentsInput>
}

export type ApprovalWorkflowUpsertWithoutCommentsInput = {
  update: Prisma.XOR<Prisma.ApprovalWorkflowUpdateWithoutCommentsInput, Prisma.ApprovalWorkflowUncheckedUpdateWithoutCommentsInput>
  create: Prisma.XOR<Prisma.ApprovalWorkflowCreateWithoutCommentsInput, Prisma.ApprovalWorkflowUncheckedCreateWithoutCommentsInput>
  where?: Prisma.ApprovalWorkflowWhereInput
}

export type ApprovalWorkflowUpdateToOneWithWhereWithoutCommentsInput = {
  where?: Prisma.ApprovalWorkflowWhereInput
  data: Prisma.XOR<Prisma.ApprovalWorkflowUpdateWithoutCommentsInput, Prisma.ApprovalWorkflowUncheckedUpdateWithoutCommentsInput>
}

export type ApprovalWorkflowUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutApprovalWorkflowNestedInput
}

export type ApprovalWorkflowUncheckedUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  currentStage?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ApprovalWorkflowCountOutputType
 */

export type ApprovalWorkflowCountOutputType = {
  comments: number
}

export type ApprovalWorkflowCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | ApprovalWorkflowCountOutputTypeCountCommentsArgs
}

/**
 * ApprovalWorkflowCountOutputType without action
 */
export type ApprovalWorkflowCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflowCountOutputType
   */
  select?: Prisma.ApprovalWorkflowCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ApprovalWorkflowCountOutputType without action
 */
export type ApprovalWorkflowCountOutputTypeCountCommentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowCommentWhereInput
}


export type ApprovalWorkflowSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  currentStage?: boolean
  assignedTo?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  comments?: boolean | Prisma.ApprovalWorkflow$commentsArgs<ExtArgs>
  _count?: boolean | Prisma.ApprovalWorkflowCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalWorkflow"]>

export type ApprovalWorkflowSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  currentStage?: boolean
  assignedTo?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalWorkflow"]>

export type ApprovalWorkflowSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  currentStage?: boolean
  assignedTo?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["approvalWorkflow"]>

export type ApprovalWorkflowSelectScalar = {
  id?: boolean
  productId?: boolean
  currentStage?: boolean
  assignedTo?: boolean
  updatedAt?: boolean
}

export type ApprovalWorkflowOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "currentStage" | "assignedTo" | "updatedAt", ExtArgs["result"]["approvalWorkflow"]>
export type ApprovalWorkflowInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  comments?: boolean | Prisma.ApprovalWorkflow$commentsArgs<ExtArgs>
  _count?: boolean | Prisma.ApprovalWorkflowCountOutputTypeDefaultArgs<ExtArgs>
}
export type ApprovalWorkflowIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ApprovalWorkflowIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ApprovalWorkflowPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApprovalWorkflow"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    comments: Prisma.$WorkflowCommentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    currentStage: string
    assignedTo: string | null
    updatedAt: Date
  }, ExtArgs["result"]["approvalWorkflow"]>
  composites: {}
}

export type ApprovalWorkflowGetPayload<S extends boolean | null | undefined | ApprovalWorkflowDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload, S>

export type ApprovalWorkflowCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApprovalWorkflowFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApprovalWorkflowCountAggregateInputType | true
  }

export interface ApprovalWorkflowDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApprovalWorkflow'], meta: { name: 'ApprovalWorkflow' } }
  /**
   * Find zero or one ApprovalWorkflow that matches the filter.
   * @param {ApprovalWorkflowFindUniqueArgs} args - Arguments to find a ApprovalWorkflow
   * @example
   * // Get one ApprovalWorkflow
   * const approvalWorkflow = await prisma.approvalWorkflow.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApprovalWorkflowFindUniqueArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApprovalWorkflow that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApprovalWorkflowFindUniqueOrThrowArgs} args - Arguments to find a ApprovalWorkflow
   * @example
   * // Get one ApprovalWorkflow
   * const approvalWorkflow = await prisma.approvalWorkflow.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApprovalWorkflowFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApprovalWorkflow that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowFindFirstArgs} args - Arguments to find a ApprovalWorkflow
   * @example
   * // Get one ApprovalWorkflow
   * const approvalWorkflow = await prisma.approvalWorkflow.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApprovalWorkflowFindFirstArgs>(args?: Prisma.SelectSubset<T, ApprovalWorkflowFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApprovalWorkflow that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowFindFirstOrThrowArgs} args - Arguments to find a ApprovalWorkflow
   * @example
   * // Get one ApprovalWorkflow
   * const approvalWorkflow = await prisma.approvalWorkflow.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApprovalWorkflowFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApprovalWorkflowFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApprovalWorkflows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApprovalWorkflows
   * const approvalWorkflows = await prisma.approvalWorkflow.findMany()
   * 
   * // Get first 10 ApprovalWorkflows
   * const approvalWorkflows = await prisma.approvalWorkflow.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const approvalWorkflowWithIdOnly = await prisma.approvalWorkflow.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApprovalWorkflowFindManyArgs>(args?: Prisma.SelectSubset<T, ApprovalWorkflowFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApprovalWorkflow.
   * @param {ApprovalWorkflowCreateArgs} args - Arguments to create a ApprovalWorkflow.
   * @example
   * // Create one ApprovalWorkflow
   * const ApprovalWorkflow = await prisma.approvalWorkflow.create({
   *   data: {
   *     // ... data to create a ApprovalWorkflow
   *   }
   * })
   * 
   */
  create<T extends ApprovalWorkflowCreateArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowCreateArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApprovalWorkflows.
   * @param {ApprovalWorkflowCreateManyArgs} args - Arguments to create many ApprovalWorkflows.
   * @example
   * // Create many ApprovalWorkflows
   * const approvalWorkflow = await prisma.approvalWorkflow.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApprovalWorkflowCreateManyArgs>(args?: Prisma.SelectSubset<T, ApprovalWorkflowCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApprovalWorkflows and returns the data saved in the database.
   * @param {ApprovalWorkflowCreateManyAndReturnArgs} args - Arguments to create many ApprovalWorkflows.
   * @example
   * // Create many ApprovalWorkflows
   * const approvalWorkflow = await prisma.approvalWorkflow.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApprovalWorkflows and only return the `id`
   * const approvalWorkflowWithIdOnly = await prisma.approvalWorkflow.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApprovalWorkflowCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApprovalWorkflowCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApprovalWorkflow.
   * @param {ApprovalWorkflowDeleteArgs} args - Arguments to delete one ApprovalWorkflow.
   * @example
   * // Delete one ApprovalWorkflow
   * const ApprovalWorkflow = await prisma.approvalWorkflow.delete({
   *   where: {
   *     // ... filter to delete one ApprovalWorkflow
   *   }
   * })
   * 
   */
  delete<T extends ApprovalWorkflowDeleteArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowDeleteArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApprovalWorkflow.
   * @param {ApprovalWorkflowUpdateArgs} args - Arguments to update one ApprovalWorkflow.
   * @example
   * // Update one ApprovalWorkflow
   * const approvalWorkflow = await prisma.approvalWorkflow.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApprovalWorkflowUpdateArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowUpdateArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApprovalWorkflows.
   * @param {ApprovalWorkflowDeleteManyArgs} args - Arguments to filter ApprovalWorkflows to delete.
   * @example
   * // Delete a few ApprovalWorkflows
   * const { count } = await prisma.approvalWorkflow.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApprovalWorkflowDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApprovalWorkflowDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApprovalWorkflows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApprovalWorkflows
   * const approvalWorkflow = await prisma.approvalWorkflow.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApprovalWorkflowUpdateManyArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApprovalWorkflows and returns the data updated in the database.
   * @param {ApprovalWorkflowUpdateManyAndReturnArgs} args - Arguments to update many ApprovalWorkflows.
   * @example
   * // Update many ApprovalWorkflows
   * const approvalWorkflow = await prisma.approvalWorkflow.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApprovalWorkflows and only return the `id`
   * const approvalWorkflowWithIdOnly = await prisma.approvalWorkflow.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApprovalWorkflowUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApprovalWorkflow.
   * @param {ApprovalWorkflowUpsertArgs} args - Arguments to update or create a ApprovalWorkflow.
   * @example
   * // Update or create a ApprovalWorkflow
   * const approvalWorkflow = await prisma.approvalWorkflow.upsert({
   *   create: {
   *     // ... data to create a ApprovalWorkflow
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApprovalWorkflow we want to update
   *   }
   * })
   */
  upsert<T extends ApprovalWorkflowUpsertArgs>(args: Prisma.SelectSubset<T, ApprovalWorkflowUpsertArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApprovalWorkflows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowCountArgs} args - Arguments to filter ApprovalWorkflows to count.
   * @example
   * // Count the number of ApprovalWorkflows
   * const count = await prisma.approvalWorkflow.count({
   *   where: {
   *     // ... the filter for the ApprovalWorkflows we want to count
   *   }
   * })
  **/
  count<T extends ApprovalWorkflowCountArgs>(
    args?: Prisma.Subset<T, ApprovalWorkflowCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApprovalWorkflowCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApprovalWorkflow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApprovalWorkflowAggregateArgs>(args: Prisma.Subset<T, ApprovalWorkflowAggregateArgs>): Prisma.PrismaPromise<GetApprovalWorkflowAggregateType<T>>

  /**
   * Group by ApprovalWorkflow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApprovalWorkflowGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApprovalWorkflowGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApprovalWorkflowGroupByArgs['orderBy'] }
      : { orderBy?: ApprovalWorkflowGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApprovalWorkflowGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApprovalWorkflowGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApprovalWorkflow model
 */
readonly fields: ApprovalWorkflowFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApprovalWorkflow.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApprovalWorkflowClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  comments<T extends Prisma.ApprovalWorkflow$commentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApprovalWorkflow$commentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApprovalWorkflow model
 */
export interface ApprovalWorkflowFieldRefs {
  readonly id: Prisma.FieldRef<"ApprovalWorkflow", 'String'>
  readonly productId: Prisma.FieldRef<"ApprovalWorkflow", 'String'>
  readonly currentStage: Prisma.FieldRef<"ApprovalWorkflow", 'String'>
  readonly assignedTo: Prisma.FieldRef<"ApprovalWorkflow", 'String'>
  readonly updatedAt: Prisma.FieldRef<"ApprovalWorkflow", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ApprovalWorkflow findUnique
 */
export type ApprovalWorkflowFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalWorkflow to fetch.
   */
  where: Prisma.ApprovalWorkflowWhereUniqueInput
}

/**
 * ApprovalWorkflow findUniqueOrThrow
 */
export type ApprovalWorkflowFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalWorkflow to fetch.
   */
  where: Prisma.ApprovalWorkflowWhereUniqueInput
}

/**
 * ApprovalWorkflow findFirst
 */
export type ApprovalWorkflowFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalWorkflow to fetch.
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalWorkflows to fetch.
   */
  orderBy?: Prisma.ApprovalWorkflowOrderByWithRelationInput | Prisma.ApprovalWorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApprovalWorkflows.
   */
  cursor?: Prisma.ApprovalWorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalWorkflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalWorkflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalWorkflows.
   */
  distinct?: Prisma.ApprovalWorkflowScalarFieldEnum | Prisma.ApprovalWorkflowScalarFieldEnum[]
}

/**
 * ApprovalWorkflow findFirstOrThrow
 */
export type ApprovalWorkflowFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalWorkflow to fetch.
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalWorkflows to fetch.
   */
  orderBy?: Prisma.ApprovalWorkflowOrderByWithRelationInput | Prisma.ApprovalWorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApprovalWorkflows.
   */
  cursor?: Prisma.ApprovalWorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalWorkflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalWorkflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalWorkflows.
   */
  distinct?: Prisma.ApprovalWorkflowScalarFieldEnum | Prisma.ApprovalWorkflowScalarFieldEnum[]
}

/**
 * ApprovalWorkflow findMany
 */
export type ApprovalWorkflowFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * Filter, which ApprovalWorkflows to fetch.
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApprovalWorkflows to fetch.
   */
  orderBy?: Prisma.ApprovalWorkflowOrderByWithRelationInput | Prisma.ApprovalWorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApprovalWorkflows.
   */
  cursor?: Prisma.ApprovalWorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApprovalWorkflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApprovalWorkflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApprovalWorkflows.
   */
  distinct?: Prisma.ApprovalWorkflowScalarFieldEnum | Prisma.ApprovalWorkflowScalarFieldEnum[]
}

/**
 * ApprovalWorkflow create
 */
export type ApprovalWorkflowCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * The data needed to create a ApprovalWorkflow.
   */
  data: Prisma.XOR<Prisma.ApprovalWorkflowCreateInput, Prisma.ApprovalWorkflowUncheckedCreateInput>
}

/**
 * ApprovalWorkflow createMany
 */
export type ApprovalWorkflowCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApprovalWorkflows.
   */
  data: Prisma.ApprovalWorkflowCreateManyInput | Prisma.ApprovalWorkflowCreateManyInput[]
}

/**
 * ApprovalWorkflow createManyAndReturn
 */
export type ApprovalWorkflowCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * The data used to create many ApprovalWorkflows.
   */
  data: Prisma.ApprovalWorkflowCreateManyInput | Prisma.ApprovalWorkflowCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ApprovalWorkflow update
 */
export type ApprovalWorkflowUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * The data needed to update a ApprovalWorkflow.
   */
  data: Prisma.XOR<Prisma.ApprovalWorkflowUpdateInput, Prisma.ApprovalWorkflowUncheckedUpdateInput>
  /**
   * Choose, which ApprovalWorkflow to update.
   */
  where: Prisma.ApprovalWorkflowWhereUniqueInput
}

/**
 * ApprovalWorkflow updateMany
 */
export type ApprovalWorkflowUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApprovalWorkflows.
   */
  data: Prisma.XOR<Prisma.ApprovalWorkflowUpdateManyMutationInput, Prisma.ApprovalWorkflowUncheckedUpdateManyInput>
  /**
   * Filter which ApprovalWorkflows to update
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * Limit how many ApprovalWorkflows to update.
   */
  limit?: number
}

/**
 * ApprovalWorkflow updateManyAndReturn
 */
export type ApprovalWorkflowUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * The data used to update ApprovalWorkflows.
   */
  data: Prisma.XOR<Prisma.ApprovalWorkflowUpdateManyMutationInput, Prisma.ApprovalWorkflowUncheckedUpdateManyInput>
  /**
   * Filter which ApprovalWorkflows to update
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * Limit how many ApprovalWorkflows to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ApprovalWorkflow upsert
 */
export type ApprovalWorkflowUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * The filter to search for the ApprovalWorkflow to update in case it exists.
   */
  where: Prisma.ApprovalWorkflowWhereUniqueInput
  /**
   * In case the ApprovalWorkflow found by the `where` argument doesn't exist, create a new ApprovalWorkflow with this data.
   */
  create: Prisma.XOR<Prisma.ApprovalWorkflowCreateInput, Prisma.ApprovalWorkflowUncheckedCreateInput>
  /**
   * In case the ApprovalWorkflow was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApprovalWorkflowUpdateInput, Prisma.ApprovalWorkflowUncheckedUpdateInput>
}

/**
 * ApprovalWorkflow delete
 */
export type ApprovalWorkflowDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
  /**
   * Filter which ApprovalWorkflow to delete.
   */
  where: Prisma.ApprovalWorkflowWhereUniqueInput
}

/**
 * ApprovalWorkflow deleteMany
 */
export type ApprovalWorkflowDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApprovalWorkflows to delete
   */
  where?: Prisma.ApprovalWorkflowWhereInput
  /**
   * Limit how many ApprovalWorkflows to delete.
   */
  limit?: number
}

/**
 * ApprovalWorkflow.comments
 */
export type ApprovalWorkflow$commentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  where?: Prisma.WorkflowCommentWhereInput
  orderBy?: Prisma.WorkflowCommentOrderByWithRelationInput | Prisma.WorkflowCommentOrderByWithRelationInput[]
  cursor?: Prisma.WorkflowCommentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkflowCommentScalarFieldEnum | Prisma.WorkflowCommentScalarFieldEnum[]
}

/**
 * ApprovalWorkflow without action
 */
export type ApprovalWorkflowDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApprovalWorkflow
   */
  select?: Prisma.ApprovalWorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApprovalWorkflow
   */
  omit?: Prisma.ApprovalWorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApprovalWorkflowInclude<ExtArgs> | null
}
