
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CulturalStory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CulturalStory
 * 
 */
export type CulturalStoryModel = runtime.Types.Result.DefaultSelection<Prisma.$CulturalStoryPayload>

export type AggregateCulturalStory = {
  _count: CulturalStoryCountAggregateOutputType | null
  _min: CulturalStoryMinAggregateOutputType | null
  _max: CulturalStoryMaxAggregateOutputType | null
}

export type CulturalStoryMinAggregateOutputType = {
  id: string | null
  productId: string | null
  artisanName: string | null
  artisanLocation: string | null
  artisanImage: string | null
  history: string | null
  culturalSignificance: string | null
  productionMethod: string | null
  geographicalIdentity: string | null
  awards: string | null
}

export type CulturalStoryMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  artisanName: string | null
  artisanLocation: string | null
  artisanImage: string | null
  history: string | null
  culturalSignificance: string | null
  productionMethod: string | null
  geographicalIdentity: string | null
  awards: string | null
}

export type CulturalStoryCountAggregateOutputType = {
  id: number
  productId: number
  artisanName: number
  artisanLocation: number
  artisanImage: number
  history: number
  culturalSignificance: number
  productionMethod: number
  geographicalIdentity: number
  awards: number
  _all: number
}


export type CulturalStoryMinAggregateInputType = {
  id?: true
  productId?: true
  artisanName?: true
  artisanLocation?: true
  artisanImage?: true
  history?: true
  culturalSignificance?: true
  productionMethod?: true
  geographicalIdentity?: true
  awards?: true
}

export type CulturalStoryMaxAggregateInputType = {
  id?: true
  productId?: true
  artisanName?: true
  artisanLocation?: true
  artisanImage?: true
  history?: true
  culturalSignificance?: true
  productionMethod?: true
  geographicalIdentity?: true
  awards?: true
}

export type CulturalStoryCountAggregateInputType = {
  id?: true
  productId?: true
  artisanName?: true
  artisanLocation?: true
  artisanImage?: true
  history?: true
  culturalSignificance?: true
  productionMethod?: true
  geographicalIdentity?: true
  awards?: true
  _all?: true
}

export type CulturalStoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CulturalStory to aggregate.
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CulturalStories to fetch.
   */
  orderBy?: Prisma.CulturalStoryOrderByWithRelationInput | Prisma.CulturalStoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CulturalStoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CulturalStories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CulturalStories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CulturalStories
  **/
  _count?: true | CulturalStoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CulturalStoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CulturalStoryMaxAggregateInputType
}

export type GetCulturalStoryAggregateType<T extends CulturalStoryAggregateArgs> = {
      [P in keyof T & keyof AggregateCulturalStory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCulturalStory[P]>
    : Prisma.GetScalarType<T[P], AggregateCulturalStory[P]>
}




export type CulturalStoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CulturalStoryWhereInput
  orderBy?: Prisma.CulturalStoryOrderByWithAggregationInput | Prisma.CulturalStoryOrderByWithAggregationInput[]
  by: Prisma.CulturalStoryScalarFieldEnum[] | Prisma.CulturalStoryScalarFieldEnum
  having?: Prisma.CulturalStoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CulturalStoryCountAggregateInputType | true
  _min?: CulturalStoryMinAggregateInputType
  _max?: CulturalStoryMaxAggregateInputType
}

export type CulturalStoryGroupByOutputType = {
  id: string
  productId: string
  artisanName: string
  artisanLocation: string
  artisanImage: string | null
  history: string
  culturalSignificance: string
  productionMethod: string
  geographicalIdentity: string | null
  awards: string | null
  _count: CulturalStoryCountAggregateOutputType | null
  _min: CulturalStoryMinAggregateOutputType | null
  _max: CulturalStoryMaxAggregateOutputType | null
}

export type GetCulturalStoryGroupByPayload<T extends CulturalStoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CulturalStoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CulturalStoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CulturalStoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CulturalStoryGroupByOutputType[P]>
      }
    >
  >



export type CulturalStoryWhereInput = {
  AND?: Prisma.CulturalStoryWhereInput | Prisma.CulturalStoryWhereInput[]
  OR?: Prisma.CulturalStoryWhereInput[]
  NOT?: Prisma.CulturalStoryWhereInput | Prisma.CulturalStoryWhereInput[]
  id?: Prisma.StringFilter<"CulturalStory"> | string
  productId?: Prisma.StringFilter<"CulturalStory"> | string
  artisanName?: Prisma.StringFilter<"CulturalStory"> | string
  artisanLocation?: Prisma.StringFilter<"CulturalStory"> | string
  artisanImage?: Prisma.StringNullableFilter<"CulturalStory"> | string | null
  history?: Prisma.StringFilter<"CulturalStory"> | string
  culturalSignificance?: Prisma.StringFilter<"CulturalStory"> | string
  productionMethod?: Prisma.StringFilter<"CulturalStory"> | string
  geographicalIdentity?: Prisma.StringNullableFilter<"CulturalStory"> | string | null
  awards?: Prisma.StringNullableFilter<"CulturalStory"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type CulturalStoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  artisanName?: Prisma.SortOrder
  artisanLocation?: Prisma.SortOrder
  artisanImage?: Prisma.SortOrderInput | Prisma.SortOrder
  history?: Prisma.SortOrder
  culturalSignificance?: Prisma.SortOrder
  productionMethod?: Prisma.SortOrder
  geographicalIdentity?: Prisma.SortOrderInput | Prisma.SortOrder
  awards?: Prisma.SortOrderInput | Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type CulturalStoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  productId?: string
  AND?: Prisma.CulturalStoryWhereInput | Prisma.CulturalStoryWhereInput[]
  OR?: Prisma.CulturalStoryWhereInput[]
  NOT?: Prisma.CulturalStoryWhereInput | Prisma.CulturalStoryWhereInput[]
  artisanName?: Prisma.StringFilter<"CulturalStory"> | string
  artisanLocation?: Prisma.StringFilter<"CulturalStory"> | string
  artisanImage?: Prisma.StringNullableFilter<"CulturalStory"> | string | null
  history?: Prisma.StringFilter<"CulturalStory"> | string
  culturalSignificance?: Prisma.StringFilter<"CulturalStory"> | string
  productionMethod?: Prisma.StringFilter<"CulturalStory"> | string
  geographicalIdentity?: Prisma.StringNullableFilter<"CulturalStory"> | string | null
  awards?: Prisma.StringNullableFilter<"CulturalStory"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "productId">

export type CulturalStoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  artisanName?: Prisma.SortOrder
  artisanLocation?: Prisma.SortOrder
  artisanImage?: Prisma.SortOrderInput | Prisma.SortOrder
  history?: Prisma.SortOrder
  culturalSignificance?: Prisma.SortOrder
  productionMethod?: Prisma.SortOrder
  geographicalIdentity?: Prisma.SortOrderInput | Prisma.SortOrder
  awards?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CulturalStoryCountOrderByAggregateInput
  _max?: Prisma.CulturalStoryMaxOrderByAggregateInput
  _min?: Prisma.CulturalStoryMinOrderByAggregateInput
}

export type CulturalStoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.CulturalStoryScalarWhereWithAggregatesInput | Prisma.CulturalStoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.CulturalStoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CulturalStoryScalarWhereWithAggregatesInput | Prisma.CulturalStoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  productId?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  artisanName?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  artisanLocation?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  artisanImage?: Prisma.StringNullableWithAggregatesFilter<"CulturalStory"> | string | null
  history?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  culturalSignificance?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  productionMethod?: Prisma.StringWithAggregatesFilter<"CulturalStory"> | string
  geographicalIdentity?: Prisma.StringNullableWithAggregatesFilter<"CulturalStory"> | string | null
  awards?: Prisma.StringNullableWithAggregatesFilter<"CulturalStory"> | string | null
}

export type CulturalStoryCreateInput = {
  id?: string
  artisanName: string
  artisanLocation: string
  artisanImage?: string | null
  history: string
  culturalSignificance: string
  productionMethod: string
  geographicalIdentity?: string | null
  awards?: string | null
  product: Prisma.ProductCreateNestedOneWithoutCulturalStoryInput
}

export type CulturalStoryUncheckedCreateInput = {
  id?: string
  productId: string
  artisanName: string
  artisanLocation: string
  artisanImage?: string | null
  history: string
  culturalSignificance: string
  productionMethod: string
  geographicalIdentity?: string | null
  awards?: string | null
}

export type CulturalStoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  artisanName?: Prisma.StringFieldUpdateOperationsInput | string
  artisanLocation?: Prisma.StringFieldUpdateOperationsInput | string
  artisanImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.StringFieldUpdateOperationsInput | string
  culturalSignificance?: Prisma.StringFieldUpdateOperationsInput | string
  productionMethod?: Prisma.StringFieldUpdateOperationsInput | string
  geographicalIdentity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  awards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutCulturalStoryNestedInput
}

export type CulturalStoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  artisanName?: Prisma.StringFieldUpdateOperationsInput | string
  artisanLocation?: Prisma.StringFieldUpdateOperationsInput | string
  artisanImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.StringFieldUpdateOperationsInput | string
  culturalSignificance?: Prisma.StringFieldUpdateOperationsInput | string
  productionMethod?: Prisma.StringFieldUpdateOperationsInput | string
  geographicalIdentity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  awards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CulturalStoryCreateManyInput = {
  id?: string
  productId: string
  artisanName: string
  artisanLocation: string
  artisanImage?: string | null
  history: string
  culturalSignificance: string
  productionMethod: string
  geographicalIdentity?: string | null
  awards?: string | null
}

export type CulturalStoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  artisanName?: Prisma.StringFieldUpdateOperationsInput | string
  artisanLocation?: Prisma.StringFieldUpdateOperationsInput | string
  artisanImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.StringFieldUpdateOperationsInput | string
  culturalSignificance?: Prisma.StringFieldUpdateOperationsInput | string
  productionMethod?: Prisma.StringFieldUpdateOperationsInput | string
  geographicalIdentity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  awards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CulturalStoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  artisanName?: Prisma.StringFieldUpdateOperationsInput | string
  artisanLocation?: Prisma.StringFieldUpdateOperationsInput | string
  artisanImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.StringFieldUpdateOperationsInput | string
  culturalSignificance?: Prisma.StringFieldUpdateOperationsInput | string
  productionMethod?: Prisma.StringFieldUpdateOperationsInput | string
  geographicalIdentity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  awards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CulturalStoryNullableScalarRelationFilter = {
  is?: Prisma.CulturalStoryWhereInput | null
  isNot?: Prisma.CulturalStoryWhereInput | null
}

export type CulturalStoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  artisanName?: Prisma.SortOrder
  artisanLocation?: Prisma.SortOrder
  artisanImage?: Prisma.SortOrder
  history?: Prisma.SortOrder
  culturalSignificance?: Prisma.SortOrder
  productionMethod?: Prisma.SortOrder
  geographicalIdentity?: Prisma.SortOrder
  awards?: Prisma.SortOrder
}

export type CulturalStoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  artisanName?: Prisma.SortOrder
  artisanLocation?: Prisma.SortOrder
  artisanImage?: Prisma.SortOrder
  history?: Prisma.SortOrder
  culturalSignificance?: Prisma.SortOrder
  productionMethod?: Prisma.SortOrder
  geographicalIdentity?: Prisma.SortOrder
  awards?: Prisma.SortOrder
}

export type CulturalStoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  artisanName?: Prisma.SortOrder
  artisanLocation?: Prisma.SortOrder
  artisanImage?: Prisma.SortOrder
  history?: Prisma.SortOrder
  culturalSignificance?: Prisma.SortOrder
  productionMethod?: Prisma.SortOrder
  geographicalIdentity?: Prisma.SortOrder
  awards?: Prisma.SortOrder
}

export type CulturalStoryCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.CulturalStoryCreateWithoutProductInput, Prisma.CulturalStoryUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.CulturalStoryCreateOrConnectWithoutProductInput
  connect?: Prisma.CulturalStoryWhereUniqueInput
}

export type CulturalStoryUncheckedCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.CulturalStoryCreateWithoutProductInput, Prisma.CulturalStoryUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.CulturalStoryCreateOrConnectWithoutProductInput
  connect?: Prisma.CulturalStoryWhereUniqueInput
}

export type CulturalStoryUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.CulturalStoryCreateWithoutProductInput, Prisma.CulturalStoryUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.CulturalStoryCreateOrConnectWithoutProductInput
  upsert?: Prisma.CulturalStoryUpsertWithoutProductInput
  disconnect?: Prisma.CulturalStoryWhereInput | boolean
  delete?: Prisma.CulturalStoryWhereInput | boolean
  connect?: Prisma.CulturalStoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CulturalStoryUpdateToOneWithWhereWithoutProductInput, Prisma.CulturalStoryUpdateWithoutProductInput>, Prisma.CulturalStoryUncheckedUpdateWithoutProductInput>
}

export type CulturalStoryUncheckedUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.CulturalStoryCreateWithoutProductInput, Prisma.CulturalStoryUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.CulturalStoryCreateOrConnectWithoutProductInput
  upsert?: Prisma.CulturalStoryUpsertWithoutProductInput
  disconnect?: Prisma.CulturalStoryWhereInput | boolean
  delete?: Prisma.CulturalStoryWhereInput | boolean
  connect?: Prisma.CulturalStoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CulturalStoryUpdateToOneWithWhereWithoutProductInput, Prisma.CulturalStoryUpdateWithoutProductInput>, Prisma.CulturalStoryUncheckedUpdateWithoutProductInput>
}

export type CulturalStoryCreateWithoutProductInput = {
  id?: string
  artisanName: string
  artisanLocation: string
  artisanImage?: string | null
  history: string
  culturalSignificance: string
  productionMethod: string
  geographicalIdentity?: string | null
  awards?: string | null
}

export type CulturalStoryUncheckedCreateWithoutProductInput = {
  id?: string
  artisanName: string
  artisanLocation: string
  artisanImage?: string | null
  history: string
  culturalSignificance: string
  productionMethod: string
  geographicalIdentity?: string | null
  awards?: string | null
}

export type CulturalStoryCreateOrConnectWithoutProductInput = {
  where: Prisma.CulturalStoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CulturalStoryCreateWithoutProductInput, Prisma.CulturalStoryUncheckedCreateWithoutProductInput>
}

export type CulturalStoryUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.CulturalStoryUpdateWithoutProductInput, Prisma.CulturalStoryUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.CulturalStoryCreateWithoutProductInput, Prisma.CulturalStoryUncheckedCreateWithoutProductInput>
  where?: Prisma.CulturalStoryWhereInput
}

export type CulturalStoryUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.CulturalStoryWhereInput
  data: Prisma.XOR<Prisma.CulturalStoryUpdateWithoutProductInput, Prisma.CulturalStoryUncheckedUpdateWithoutProductInput>
}

export type CulturalStoryUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  artisanName?: Prisma.StringFieldUpdateOperationsInput | string
  artisanLocation?: Prisma.StringFieldUpdateOperationsInput | string
  artisanImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.StringFieldUpdateOperationsInput | string
  culturalSignificance?: Prisma.StringFieldUpdateOperationsInput | string
  productionMethod?: Prisma.StringFieldUpdateOperationsInput | string
  geographicalIdentity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  awards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CulturalStoryUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  artisanName?: Prisma.StringFieldUpdateOperationsInput | string
  artisanLocation?: Prisma.StringFieldUpdateOperationsInput | string
  artisanImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  history?: Prisma.StringFieldUpdateOperationsInput | string
  culturalSignificance?: Prisma.StringFieldUpdateOperationsInput | string
  productionMethod?: Prisma.StringFieldUpdateOperationsInput | string
  geographicalIdentity?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  awards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type CulturalStorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  artisanName?: boolean
  artisanLocation?: boolean
  artisanImage?: boolean
  history?: boolean
  culturalSignificance?: boolean
  productionMethod?: boolean
  geographicalIdentity?: boolean
  awards?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["culturalStory"]>

export type CulturalStorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  artisanName?: boolean
  artisanLocation?: boolean
  artisanImage?: boolean
  history?: boolean
  culturalSignificance?: boolean
  productionMethod?: boolean
  geographicalIdentity?: boolean
  awards?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["culturalStory"]>

export type CulturalStorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  artisanName?: boolean
  artisanLocation?: boolean
  artisanImage?: boolean
  history?: boolean
  culturalSignificance?: boolean
  productionMethod?: boolean
  geographicalIdentity?: boolean
  awards?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["culturalStory"]>

export type CulturalStorySelectScalar = {
  id?: boolean
  productId?: boolean
  artisanName?: boolean
  artisanLocation?: boolean
  artisanImage?: boolean
  history?: boolean
  culturalSignificance?: boolean
  productionMethod?: boolean
  geographicalIdentity?: boolean
  awards?: boolean
}

export type CulturalStoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "artisanName" | "artisanLocation" | "artisanImage" | "history" | "culturalSignificance" | "productionMethod" | "geographicalIdentity" | "awards", ExtArgs["result"]["culturalStory"]>
export type CulturalStoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type CulturalStoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type CulturalStoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $CulturalStoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CulturalStory"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    artisanName: string
    artisanLocation: string
    artisanImage: string | null
    history: string
    culturalSignificance: string
    productionMethod: string
    geographicalIdentity: string | null
    awards: string | null
  }, ExtArgs["result"]["culturalStory"]>
  composites: {}
}

export type CulturalStoryGetPayload<S extends boolean | null | undefined | CulturalStoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload, S>

export type CulturalStoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CulturalStoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CulturalStoryCountAggregateInputType | true
  }

export interface CulturalStoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CulturalStory'], meta: { name: 'CulturalStory' } }
  /**
   * Find zero or one CulturalStory that matches the filter.
   * @param {CulturalStoryFindUniqueArgs} args - Arguments to find a CulturalStory
   * @example
   * // Get one CulturalStory
   * const culturalStory = await prisma.culturalStory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CulturalStoryFindUniqueArgs>(args: Prisma.SelectSubset<T, CulturalStoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CulturalStory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CulturalStoryFindUniqueOrThrowArgs} args - Arguments to find a CulturalStory
   * @example
   * // Get one CulturalStory
   * const culturalStory = await prisma.culturalStory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CulturalStoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CulturalStoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CulturalStory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryFindFirstArgs} args - Arguments to find a CulturalStory
   * @example
   * // Get one CulturalStory
   * const culturalStory = await prisma.culturalStory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CulturalStoryFindFirstArgs>(args?: Prisma.SelectSubset<T, CulturalStoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CulturalStory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryFindFirstOrThrowArgs} args - Arguments to find a CulturalStory
   * @example
   * // Get one CulturalStory
   * const culturalStory = await prisma.culturalStory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CulturalStoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CulturalStoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CulturalStories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CulturalStories
   * const culturalStories = await prisma.culturalStory.findMany()
   * 
   * // Get first 10 CulturalStories
   * const culturalStories = await prisma.culturalStory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const culturalStoryWithIdOnly = await prisma.culturalStory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CulturalStoryFindManyArgs>(args?: Prisma.SelectSubset<T, CulturalStoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CulturalStory.
   * @param {CulturalStoryCreateArgs} args - Arguments to create a CulturalStory.
   * @example
   * // Create one CulturalStory
   * const CulturalStory = await prisma.culturalStory.create({
   *   data: {
   *     // ... data to create a CulturalStory
   *   }
   * })
   * 
   */
  create<T extends CulturalStoryCreateArgs>(args: Prisma.SelectSubset<T, CulturalStoryCreateArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CulturalStories.
   * @param {CulturalStoryCreateManyArgs} args - Arguments to create many CulturalStories.
   * @example
   * // Create many CulturalStories
   * const culturalStory = await prisma.culturalStory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CulturalStoryCreateManyArgs>(args?: Prisma.SelectSubset<T, CulturalStoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CulturalStories and returns the data saved in the database.
   * @param {CulturalStoryCreateManyAndReturnArgs} args - Arguments to create many CulturalStories.
   * @example
   * // Create many CulturalStories
   * const culturalStory = await prisma.culturalStory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CulturalStories and only return the `id`
   * const culturalStoryWithIdOnly = await prisma.culturalStory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CulturalStoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CulturalStoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CulturalStory.
   * @param {CulturalStoryDeleteArgs} args - Arguments to delete one CulturalStory.
   * @example
   * // Delete one CulturalStory
   * const CulturalStory = await prisma.culturalStory.delete({
   *   where: {
   *     // ... filter to delete one CulturalStory
   *   }
   * })
   * 
   */
  delete<T extends CulturalStoryDeleteArgs>(args: Prisma.SelectSubset<T, CulturalStoryDeleteArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CulturalStory.
   * @param {CulturalStoryUpdateArgs} args - Arguments to update one CulturalStory.
   * @example
   * // Update one CulturalStory
   * const culturalStory = await prisma.culturalStory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CulturalStoryUpdateArgs>(args: Prisma.SelectSubset<T, CulturalStoryUpdateArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CulturalStories.
   * @param {CulturalStoryDeleteManyArgs} args - Arguments to filter CulturalStories to delete.
   * @example
   * // Delete a few CulturalStories
   * const { count } = await prisma.culturalStory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CulturalStoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, CulturalStoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CulturalStories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CulturalStories
   * const culturalStory = await prisma.culturalStory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CulturalStoryUpdateManyArgs>(args: Prisma.SelectSubset<T, CulturalStoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CulturalStories and returns the data updated in the database.
   * @param {CulturalStoryUpdateManyAndReturnArgs} args - Arguments to update many CulturalStories.
   * @example
   * // Update many CulturalStories
   * const culturalStory = await prisma.culturalStory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CulturalStories and only return the `id`
   * const culturalStoryWithIdOnly = await prisma.culturalStory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CulturalStoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CulturalStoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CulturalStory.
   * @param {CulturalStoryUpsertArgs} args - Arguments to update or create a CulturalStory.
   * @example
   * // Update or create a CulturalStory
   * const culturalStory = await prisma.culturalStory.upsert({
   *   create: {
   *     // ... data to create a CulturalStory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CulturalStory we want to update
   *   }
   * })
   */
  upsert<T extends CulturalStoryUpsertArgs>(args: Prisma.SelectSubset<T, CulturalStoryUpsertArgs<ExtArgs>>): Prisma.Prisma__CulturalStoryClient<runtime.Types.Result.GetResult<Prisma.$CulturalStoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CulturalStories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryCountArgs} args - Arguments to filter CulturalStories to count.
   * @example
   * // Count the number of CulturalStories
   * const count = await prisma.culturalStory.count({
   *   where: {
   *     // ... the filter for the CulturalStories we want to count
   *   }
   * })
  **/
  count<T extends CulturalStoryCountArgs>(
    args?: Prisma.Subset<T, CulturalStoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CulturalStoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CulturalStory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CulturalStoryAggregateArgs>(args: Prisma.Subset<T, CulturalStoryAggregateArgs>): Prisma.PrismaPromise<GetCulturalStoryAggregateType<T>>

  /**
   * Group by CulturalStory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CulturalStoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CulturalStoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CulturalStoryGroupByArgs['orderBy'] }
      : { orderBy?: CulturalStoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CulturalStoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCulturalStoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CulturalStory model
 */
readonly fields: CulturalStoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CulturalStory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CulturalStoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CulturalStory model
 */
export interface CulturalStoryFieldRefs {
  readonly id: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly productId: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly artisanName: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly artisanLocation: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly artisanImage: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly history: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly culturalSignificance: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly productionMethod: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly geographicalIdentity: Prisma.FieldRef<"CulturalStory", 'String'>
  readonly awards: Prisma.FieldRef<"CulturalStory", 'String'>
}
    

// Custom InputTypes
/**
 * CulturalStory findUnique
 */
export type CulturalStoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * Filter, which CulturalStory to fetch.
   */
  where: Prisma.CulturalStoryWhereUniqueInput
}

/**
 * CulturalStory findUniqueOrThrow
 */
export type CulturalStoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * Filter, which CulturalStory to fetch.
   */
  where: Prisma.CulturalStoryWhereUniqueInput
}

/**
 * CulturalStory findFirst
 */
export type CulturalStoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * Filter, which CulturalStory to fetch.
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CulturalStories to fetch.
   */
  orderBy?: Prisma.CulturalStoryOrderByWithRelationInput | Prisma.CulturalStoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CulturalStories.
   */
  cursor?: Prisma.CulturalStoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CulturalStories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CulturalStories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CulturalStories.
   */
  distinct?: Prisma.CulturalStoryScalarFieldEnum | Prisma.CulturalStoryScalarFieldEnum[]
}

/**
 * CulturalStory findFirstOrThrow
 */
export type CulturalStoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * Filter, which CulturalStory to fetch.
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CulturalStories to fetch.
   */
  orderBy?: Prisma.CulturalStoryOrderByWithRelationInput | Prisma.CulturalStoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CulturalStories.
   */
  cursor?: Prisma.CulturalStoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CulturalStories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CulturalStories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CulturalStories.
   */
  distinct?: Prisma.CulturalStoryScalarFieldEnum | Prisma.CulturalStoryScalarFieldEnum[]
}

/**
 * CulturalStory findMany
 */
export type CulturalStoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * Filter, which CulturalStories to fetch.
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CulturalStories to fetch.
   */
  orderBy?: Prisma.CulturalStoryOrderByWithRelationInput | Prisma.CulturalStoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CulturalStories.
   */
  cursor?: Prisma.CulturalStoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CulturalStories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CulturalStories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CulturalStories.
   */
  distinct?: Prisma.CulturalStoryScalarFieldEnum | Prisma.CulturalStoryScalarFieldEnum[]
}

/**
 * CulturalStory create
 */
export type CulturalStoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * The data needed to create a CulturalStory.
   */
  data: Prisma.XOR<Prisma.CulturalStoryCreateInput, Prisma.CulturalStoryUncheckedCreateInput>
}

/**
 * CulturalStory createMany
 */
export type CulturalStoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CulturalStories.
   */
  data: Prisma.CulturalStoryCreateManyInput | Prisma.CulturalStoryCreateManyInput[]
}

/**
 * CulturalStory createManyAndReturn
 */
export type CulturalStoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * The data used to create many CulturalStories.
   */
  data: Prisma.CulturalStoryCreateManyInput | Prisma.CulturalStoryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CulturalStory update
 */
export type CulturalStoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * The data needed to update a CulturalStory.
   */
  data: Prisma.XOR<Prisma.CulturalStoryUpdateInput, Prisma.CulturalStoryUncheckedUpdateInput>
  /**
   * Choose, which CulturalStory to update.
   */
  where: Prisma.CulturalStoryWhereUniqueInput
}

/**
 * CulturalStory updateMany
 */
export type CulturalStoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CulturalStories.
   */
  data: Prisma.XOR<Prisma.CulturalStoryUpdateManyMutationInput, Prisma.CulturalStoryUncheckedUpdateManyInput>
  /**
   * Filter which CulturalStories to update
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * Limit how many CulturalStories to update.
   */
  limit?: number
}

/**
 * CulturalStory updateManyAndReturn
 */
export type CulturalStoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * The data used to update CulturalStories.
   */
  data: Prisma.XOR<Prisma.CulturalStoryUpdateManyMutationInput, Prisma.CulturalStoryUncheckedUpdateManyInput>
  /**
   * Filter which CulturalStories to update
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * Limit how many CulturalStories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CulturalStory upsert
 */
export type CulturalStoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * The filter to search for the CulturalStory to update in case it exists.
   */
  where: Prisma.CulturalStoryWhereUniqueInput
  /**
   * In case the CulturalStory found by the `where` argument doesn't exist, create a new CulturalStory with this data.
   */
  create: Prisma.XOR<Prisma.CulturalStoryCreateInput, Prisma.CulturalStoryUncheckedCreateInput>
  /**
   * In case the CulturalStory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CulturalStoryUpdateInput, Prisma.CulturalStoryUncheckedUpdateInput>
}

/**
 * CulturalStory delete
 */
export type CulturalStoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
  /**
   * Filter which CulturalStory to delete.
   */
  where: Prisma.CulturalStoryWhereUniqueInput
}

/**
 * CulturalStory deleteMany
 */
export type CulturalStoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CulturalStories to delete
   */
  where?: Prisma.CulturalStoryWhereInput
  /**
   * Limit how many CulturalStories to delete.
   */
  limit?: number
}

/**
 * CulturalStory without action
 */
export type CulturalStoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CulturalStory
   */
  select?: Prisma.CulturalStorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CulturalStory
   */
  omit?: Prisma.CulturalStoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CulturalStoryInclude<ExtArgs> | null
}
