
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FooterSocialLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FooterSocialLink
 * 
 */
export type FooterSocialLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$FooterSocialLinkPayload>

export type AggregateFooterSocialLink = {
  _count: FooterSocialLinkCountAggregateOutputType | null
  _min: FooterSocialLinkMinAggregateOutputType | null
  _max: FooterSocialLinkMaxAggregateOutputType | null
}

export type FooterSocialLinkMinAggregateOutputType = {
  id: string | null
  platform: string | null
  url: string | null
  iconText: string | null
  isEnabled: boolean | null
}

export type FooterSocialLinkMaxAggregateOutputType = {
  id: string | null
  platform: string | null
  url: string | null
  iconText: string | null
  isEnabled: boolean | null
}

export type FooterSocialLinkCountAggregateOutputType = {
  id: number
  platform: number
  url: number
  iconText: number
  isEnabled: number
  _all: number
}


export type FooterSocialLinkMinAggregateInputType = {
  id?: true
  platform?: true
  url?: true
  iconText?: true
  isEnabled?: true
}

export type FooterSocialLinkMaxAggregateInputType = {
  id?: true
  platform?: true
  url?: true
  iconText?: true
  isEnabled?: true
}

export type FooterSocialLinkCountAggregateInputType = {
  id?: true
  platform?: true
  url?: true
  iconText?: true
  isEnabled?: true
  _all?: true
}

export type FooterSocialLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterSocialLink to aggregate.
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocialLinks to fetch.
   */
  orderBy?: Prisma.FooterSocialLinkOrderByWithRelationInput | Prisma.FooterSocialLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FooterSocialLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocialLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocialLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FooterSocialLinks
  **/
  _count?: true | FooterSocialLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FooterSocialLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FooterSocialLinkMaxAggregateInputType
}

export type GetFooterSocialLinkAggregateType<T extends FooterSocialLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateFooterSocialLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFooterSocialLink[P]>
    : Prisma.GetScalarType<T[P], AggregateFooterSocialLink[P]>
}




export type FooterSocialLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterSocialLinkWhereInput
  orderBy?: Prisma.FooterSocialLinkOrderByWithAggregationInput | Prisma.FooterSocialLinkOrderByWithAggregationInput[]
  by: Prisma.FooterSocialLinkScalarFieldEnum[] | Prisma.FooterSocialLinkScalarFieldEnum
  having?: Prisma.FooterSocialLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FooterSocialLinkCountAggregateInputType | true
  _min?: FooterSocialLinkMinAggregateInputType
  _max?: FooterSocialLinkMaxAggregateInputType
}

export type FooterSocialLinkGroupByOutputType = {
  id: string
  platform: string
  url: string
  iconText: string | null
  isEnabled: boolean
  _count: FooterSocialLinkCountAggregateOutputType | null
  _min: FooterSocialLinkMinAggregateOutputType | null
  _max: FooterSocialLinkMaxAggregateOutputType | null
}

export type GetFooterSocialLinkGroupByPayload<T extends FooterSocialLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FooterSocialLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FooterSocialLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FooterSocialLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FooterSocialLinkGroupByOutputType[P]>
      }
    >
  >



export type FooterSocialLinkWhereInput = {
  AND?: Prisma.FooterSocialLinkWhereInput | Prisma.FooterSocialLinkWhereInput[]
  OR?: Prisma.FooterSocialLinkWhereInput[]
  NOT?: Prisma.FooterSocialLinkWhereInput | Prisma.FooterSocialLinkWhereInput[]
  id?: Prisma.StringFilter<"FooterSocialLink"> | string
  platform?: Prisma.StringFilter<"FooterSocialLink"> | string
  url?: Prisma.StringFilter<"FooterSocialLink"> | string
  iconText?: Prisma.StringNullableFilter<"FooterSocialLink"> | string | null
  isEnabled?: Prisma.BoolFilter<"FooterSocialLink"> | boolean
}

export type FooterSocialLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  iconText?: Prisma.SortOrderInput | Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterSocialLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  platform?: string
  AND?: Prisma.FooterSocialLinkWhereInput | Prisma.FooterSocialLinkWhereInput[]
  OR?: Prisma.FooterSocialLinkWhereInput[]
  NOT?: Prisma.FooterSocialLinkWhereInput | Prisma.FooterSocialLinkWhereInput[]
  url?: Prisma.StringFilter<"FooterSocialLink"> | string
  iconText?: Prisma.StringNullableFilter<"FooterSocialLink"> | string | null
  isEnabled?: Prisma.BoolFilter<"FooterSocialLink"> | boolean
}, "id" | "platform">

export type FooterSocialLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  iconText?: Prisma.SortOrderInput | Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  _count?: Prisma.FooterSocialLinkCountOrderByAggregateInput
  _max?: Prisma.FooterSocialLinkMaxOrderByAggregateInput
  _min?: Prisma.FooterSocialLinkMinOrderByAggregateInput
}

export type FooterSocialLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.FooterSocialLinkScalarWhereWithAggregatesInput | Prisma.FooterSocialLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.FooterSocialLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FooterSocialLinkScalarWhereWithAggregatesInput | Prisma.FooterSocialLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FooterSocialLink"> | string
  platform?: Prisma.StringWithAggregatesFilter<"FooterSocialLink"> | string
  url?: Prisma.StringWithAggregatesFilter<"FooterSocialLink"> | string
  iconText?: Prisma.StringNullableWithAggregatesFilter<"FooterSocialLink"> | string | null
  isEnabled?: Prisma.BoolWithAggregatesFilter<"FooterSocialLink"> | boolean
}

export type FooterSocialLinkCreateInput = {
  id?: string
  platform: string
  url: string
  iconText?: string | null
  isEnabled?: boolean
}

export type FooterSocialLinkUncheckedCreateInput = {
  id?: string
  platform: string
  url: string
  iconText?: string | null
  isEnabled?: boolean
}

export type FooterSocialLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  iconText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterSocialLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  iconText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterSocialLinkCreateManyInput = {
  id?: string
  platform: string
  url: string
  iconText?: string | null
  isEnabled?: boolean
}

export type FooterSocialLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  iconText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterSocialLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  iconText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterSocialLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  iconText?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterSocialLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  iconText?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterSocialLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  iconText?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}



export type FooterSocialLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  platform?: boolean
  url?: boolean
  iconText?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerSocialLink"]>

export type FooterSocialLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  platform?: boolean
  url?: boolean
  iconText?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerSocialLink"]>

export type FooterSocialLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  platform?: boolean
  url?: boolean
  iconText?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerSocialLink"]>

export type FooterSocialLinkSelectScalar = {
  id?: boolean
  platform?: boolean
  url?: boolean
  iconText?: boolean
  isEnabled?: boolean
}

export type FooterSocialLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "platform" | "url" | "iconText" | "isEnabled", ExtArgs["result"]["footerSocialLink"]>

export type $FooterSocialLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FooterSocialLink"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    platform: string
    url: string
    iconText: string | null
    isEnabled: boolean
  }, ExtArgs["result"]["footerSocialLink"]>
  composites: {}
}

export type FooterSocialLinkGetPayload<S extends boolean | null | undefined | FooterSocialLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload, S>

export type FooterSocialLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FooterSocialLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FooterSocialLinkCountAggregateInputType | true
  }

export interface FooterSocialLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FooterSocialLink'], meta: { name: 'FooterSocialLink' } }
  /**
   * Find zero or one FooterSocialLink that matches the filter.
   * @param {FooterSocialLinkFindUniqueArgs} args - Arguments to find a FooterSocialLink
   * @example
   * // Get one FooterSocialLink
   * const footerSocialLink = await prisma.footerSocialLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FooterSocialLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FooterSocialLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FooterSocialLinkFindUniqueOrThrowArgs} args - Arguments to find a FooterSocialLink
   * @example
   * // Get one FooterSocialLink
   * const footerSocialLink = await prisma.footerSocialLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FooterSocialLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterSocialLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkFindFirstArgs} args - Arguments to find a FooterSocialLink
   * @example
   * // Get one FooterSocialLink
   * const footerSocialLink = await prisma.footerSocialLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FooterSocialLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, FooterSocialLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterSocialLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkFindFirstOrThrowArgs} args - Arguments to find a FooterSocialLink
   * @example
   * // Get one FooterSocialLink
   * const footerSocialLink = await prisma.footerSocialLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FooterSocialLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FooterSocialLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FooterSocialLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FooterSocialLinks
   * const footerSocialLinks = await prisma.footerSocialLink.findMany()
   * 
   * // Get first 10 FooterSocialLinks
   * const footerSocialLinks = await prisma.footerSocialLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const footerSocialLinkWithIdOnly = await prisma.footerSocialLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FooterSocialLinkFindManyArgs>(args?: Prisma.SelectSubset<T, FooterSocialLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FooterSocialLink.
   * @param {FooterSocialLinkCreateArgs} args - Arguments to create a FooterSocialLink.
   * @example
   * // Create one FooterSocialLink
   * const FooterSocialLink = await prisma.footerSocialLink.create({
   *   data: {
   *     // ... data to create a FooterSocialLink
   *   }
   * })
   * 
   */
  create<T extends FooterSocialLinkCreateArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkCreateArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FooterSocialLinks.
   * @param {FooterSocialLinkCreateManyArgs} args - Arguments to create many FooterSocialLinks.
   * @example
   * // Create many FooterSocialLinks
   * const footerSocialLink = await prisma.footerSocialLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FooterSocialLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, FooterSocialLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FooterSocialLinks and returns the data saved in the database.
   * @param {FooterSocialLinkCreateManyAndReturnArgs} args - Arguments to create many FooterSocialLinks.
   * @example
   * // Create many FooterSocialLinks
   * const footerSocialLink = await prisma.footerSocialLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FooterSocialLinks and only return the `id`
   * const footerSocialLinkWithIdOnly = await prisma.footerSocialLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FooterSocialLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FooterSocialLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FooterSocialLink.
   * @param {FooterSocialLinkDeleteArgs} args - Arguments to delete one FooterSocialLink.
   * @example
   * // Delete one FooterSocialLink
   * const FooterSocialLink = await prisma.footerSocialLink.delete({
   *   where: {
   *     // ... filter to delete one FooterSocialLink
   *   }
   * })
   * 
   */
  delete<T extends FooterSocialLinkDeleteArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FooterSocialLink.
   * @param {FooterSocialLinkUpdateArgs} args - Arguments to update one FooterSocialLink.
   * @example
   * // Update one FooterSocialLink
   * const footerSocialLink = await prisma.footerSocialLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FooterSocialLinkUpdateArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FooterSocialLinks.
   * @param {FooterSocialLinkDeleteManyArgs} args - Arguments to filter FooterSocialLinks to delete.
   * @example
   * // Delete a few FooterSocialLinks
   * const { count } = await prisma.footerSocialLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FooterSocialLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, FooterSocialLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterSocialLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FooterSocialLinks
   * const footerSocialLink = await prisma.footerSocialLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FooterSocialLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterSocialLinks and returns the data updated in the database.
   * @param {FooterSocialLinkUpdateManyAndReturnArgs} args - Arguments to update many FooterSocialLinks.
   * @example
   * // Update many FooterSocialLinks
   * const footerSocialLink = await prisma.footerSocialLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FooterSocialLinks and only return the `id`
   * const footerSocialLinkWithIdOnly = await prisma.footerSocialLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FooterSocialLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FooterSocialLink.
   * @param {FooterSocialLinkUpsertArgs} args - Arguments to update or create a FooterSocialLink.
   * @example
   * // Update or create a FooterSocialLink
   * const footerSocialLink = await prisma.footerSocialLink.upsert({
   *   create: {
   *     // ... data to create a FooterSocialLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FooterSocialLink we want to update
   *   }
   * })
   */
  upsert<T extends FooterSocialLinkUpsertArgs>(args: Prisma.SelectSubset<T, FooterSocialLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__FooterSocialLinkClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FooterSocialLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkCountArgs} args - Arguments to filter FooterSocialLinks to count.
   * @example
   * // Count the number of FooterSocialLinks
   * const count = await prisma.footerSocialLink.count({
   *   where: {
   *     // ... the filter for the FooterSocialLinks we want to count
   *   }
   * })
  **/
  count<T extends FooterSocialLinkCountArgs>(
    args?: Prisma.Subset<T, FooterSocialLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FooterSocialLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FooterSocialLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FooterSocialLinkAggregateArgs>(args: Prisma.Subset<T, FooterSocialLinkAggregateArgs>): Prisma.PrismaPromise<GetFooterSocialLinkAggregateType<T>>

  /**
   * Group by FooterSocialLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FooterSocialLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FooterSocialLinkGroupByArgs['orderBy'] }
      : { orderBy?: FooterSocialLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FooterSocialLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFooterSocialLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FooterSocialLink model
 */
readonly fields: FooterSocialLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FooterSocialLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FooterSocialLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FooterSocialLink model
 */
export interface FooterSocialLinkFieldRefs {
  readonly id: Prisma.FieldRef<"FooterSocialLink", 'String'>
  readonly platform: Prisma.FieldRef<"FooterSocialLink", 'String'>
  readonly url: Prisma.FieldRef<"FooterSocialLink", 'String'>
  readonly iconText: Prisma.FieldRef<"FooterSocialLink", 'String'>
  readonly isEnabled: Prisma.FieldRef<"FooterSocialLink", 'Boolean'>
}
    

// Custom InputTypes
/**
 * FooterSocialLink findUnique
 */
export type FooterSocialLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * Filter, which FooterSocialLink to fetch.
   */
  where: Prisma.FooterSocialLinkWhereUniqueInput
}

/**
 * FooterSocialLink findUniqueOrThrow
 */
export type FooterSocialLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * Filter, which FooterSocialLink to fetch.
   */
  where: Prisma.FooterSocialLinkWhereUniqueInput
}

/**
 * FooterSocialLink findFirst
 */
export type FooterSocialLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * Filter, which FooterSocialLink to fetch.
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocialLinks to fetch.
   */
  orderBy?: Prisma.FooterSocialLinkOrderByWithRelationInput | Prisma.FooterSocialLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterSocialLinks.
   */
  cursor?: Prisma.FooterSocialLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocialLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocialLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterSocialLinks.
   */
  distinct?: Prisma.FooterSocialLinkScalarFieldEnum | Prisma.FooterSocialLinkScalarFieldEnum[]
}

/**
 * FooterSocialLink findFirstOrThrow
 */
export type FooterSocialLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * Filter, which FooterSocialLink to fetch.
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocialLinks to fetch.
   */
  orderBy?: Prisma.FooterSocialLinkOrderByWithRelationInput | Prisma.FooterSocialLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterSocialLinks.
   */
  cursor?: Prisma.FooterSocialLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocialLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocialLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterSocialLinks.
   */
  distinct?: Prisma.FooterSocialLinkScalarFieldEnum | Prisma.FooterSocialLinkScalarFieldEnum[]
}

/**
 * FooterSocialLink findMany
 */
export type FooterSocialLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * Filter, which FooterSocialLinks to fetch.
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocialLinks to fetch.
   */
  orderBy?: Prisma.FooterSocialLinkOrderByWithRelationInput | Prisma.FooterSocialLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FooterSocialLinks.
   */
  cursor?: Prisma.FooterSocialLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocialLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocialLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterSocialLinks.
   */
  distinct?: Prisma.FooterSocialLinkScalarFieldEnum | Prisma.FooterSocialLinkScalarFieldEnum[]
}

/**
 * FooterSocialLink create
 */
export type FooterSocialLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * The data needed to create a FooterSocialLink.
   */
  data: Prisma.XOR<Prisma.FooterSocialLinkCreateInput, Prisma.FooterSocialLinkUncheckedCreateInput>
}

/**
 * FooterSocialLink createMany
 */
export type FooterSocialLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FooterSocialLinks.
   */
  data: Prisma.FooterSocialLinkCreateManyInput | Prisma.FooterSocialLinkCreateManyInput[]
}

/**
 * FooterSocialLink createManyAndReturn
 */
export type FooterSocialLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * The data used to create many FooterSocialLinks.
   */
  data: Prisma.FooterSocialLinkCreateManyInput | Prisma.FooterSocialLinkCreateManyInput[]
}

/**
 * FooterSocialLink update
 */
export type FooterSocialLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * The data needed to update a FooterSocialLink.
   */
  data: Prisma.XOR<Prisma.FooterSocialLinkUpdateInput, Prisma.FooterSocialLinkUncheckedUpdateInput>
  /**
   * Choose, which FooterSocialLink to update.
   */
  where: Prisma.FooterSocialLinkWhereUniqueInput
}

/**
 * FooterSocialLink updateMany
 */
export type FooterSocialLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FooterSocialLinks.
   */
  data: Prisma.XOR<Prisma.FooterSocialLinkUpdateManyMutationInput, Prisma.FooterSocialLinkUncheckedUpdateManyInput>
  /**
   * Filter which FooterSocialLinks to update
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * Limit how many FooterSocialLinks to update.
   */
  limit?: number
}

/**
 * FooterSocialLink updateManyAndReturn
 */
export type FooterSocialLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * The data used to update FooterSocialLinks.
   */
  data: Prisma.XOR<Prisma.FooterSocialLinkUpdateManyMutationInput, Prisma.FooterSocialLinkUncheckedUpdateManyInput>
  /**
   * Filter which FooterSocialLinks to update
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * Limit how many FooterSocialLinks to update.
   */
  limit?: number
}

/**
 * FooterSocialLink upsert
 */
export type FooterSocialLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * The filter to search for the FooterSocialLink to update in case it exists.
   */
  where: Prisma.FooterSocialLinkWhereUniqueInput
  /**
   * In case the FooterSocialLink found by the `where` argument doesn't exist, create a new FooterSocialLink with this data.
   */
  create: Prisma.XOR<Prisma.FooterSocialLinkCreateInput, Prisma.FooterSocialLinkUncheckedCreateInput>
  /**
   * In case the FooterSocialLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FooterSocialLinkUpdateInput, Prisma.FooterSocialLinkUncheckedUpdateInput>
}

/**
 * FooterSocialLink delete
 */
export type FooterSocialLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
  /**
   * Filter which FooterSocialLink to delete.
   */
  where: Prisma.FooterSocialLinkWhereUniqueInput
}

/**
 * FooterSocialLink deleteMany
 */
export type FooterSocialLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterSocialLinks to delete
   */
  where?: Prisma.FooterSocialLinkWhereInput
  /**
   * Limit how many FooterSocialLinks to delete.
   */
  limit?: number
}

/**
 * FooterSocialLink without action
 */
export type FooterSocialLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocialLink
   */
  select?: Prisma.FooterSocialLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocialLink
   */
  omit?: Prisma.FooterSocialLinkOmit<ExtArgs> | null
}
