
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FooterCertification` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FooterCertification
 * 
 */
export type FooterCertificationModel = runtime.Types.Result.DefaultSelection<Prisma.$FooterCertificationPayload>

export type AggregateFooterCertification = {
  _count: FooterCertificationCountAggregateOutputType | null
  _min: FooterCertificationMinAggregateOutputType | null
  _max: FooterCertificationMaxAggregateOutputType | null
}

export type FooterCertificationMinAggregateOutputType = {
  id: string | null
  name: string | null
  imageUrl: string | null
  isEnabled: boolean | null
}

export type FooterCertificationMaxAggregateOutputType = {
  id: string | null
  name: string | null
  imageUrl: string | null
  isEnabled: boolean | null
}

export type FooterCertificationCountAggregateOutputType = {
  id: number
  name: number
  imageUrl: number
  isEnabled: number
  _all: number
}


export type FooterCertificationMinAggregateInputType = {
  id?: true
  name?: true
  imageUrl?: true
  isEnabled?: true
}

export type FooterCertificationMaxAggregateInputType = {
  id?: true
  name?: true
  imageUrl?: true
  isEnabled?: true
}

export type FooterCertificationCountAggregateInputType = {
  id?: true
  name?: true
  imageUrl?: true
  isEnabled?: true
  _all?: true
}

export type FooterCertificationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterCertification to aggregate.
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterCertifications to fetch.
   */
  orderBy?: Prisma.FooterCertificationOrderByWithRelationInput | Prisma.FooterCertificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FooterCertificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterCertifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterCertifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FooterCertifications
  **/
  _count?: true | FooterCertificationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FooterCertificationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FooterCertificationMaxAggregateInputType
}

export type GetFooterCertificationAggregateType<T extends FooterCertificationAggregateArgs> = {
      [P in keyof T & keyof AggregateFooterCertification]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFooterCertification[P]>
    : Prisma.GetScalarType<T[P], AggregateFooterCertification[P]>
}




export type FooterCertificationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterCertificationWhereInput
  orderBy?: Prisma.FooterCertificationOrderByWithAggregationInput | Prisma.FooterCertificationOrderByWithAggregationInput[]
  by: Prisma.FooterCertificationScalarFieldEnum[] | Prisma.FooterCertificationScalarFieldEnum
  having?: Prisma.FooterCertificationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FooterCertificationCountAggregateInputType | true
  _min?: FooterCertificationMinAggregateInputType
  _max?: FooterCertificationMaxAggregateInputType
}

export type FooterCertificationGroupByOutputType = {
  id: string
  name: string
  imageUrl: string
  isEnabled: boolean
  _count: FooterCertificationCountAggregateOutputType | null
  _min: FooterCertificationMinAggregateOutputType | null
  _max: FooterCertificationMaxAggregateOutputType | null
}

export type GetFooterCertificationGroupByPayload<T extends FooterCertificationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FooterCertificationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FooterCertificationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FooterCertificationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FooterCertificationGroupByOutputType[P]>
      }
    >
  >



export type FooterCertificationWhereInput = {
  AND?: Prisma.FooterCertificationWhereInput | Prisma.FooterCertificationWhereInput[]
  OR?: Prisma.FooterCertificationWhereInput[]
  NOT?: Prisma.FooterCertificationWhereInput | Prisma.FooterCertificationWhereInput[]
  id?: Prisma.StringFilter<"FooterCertification"> | string
  name?: Prisma.StringFilter<"FooterCertification"> | string
  imageUrl?: Prisma.StringFilter<"FooterCertification"> | string
  isEnabled?: Prisma.BoolFilter<"FooterCertification"> | boolean
}

export type FooterCertificationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterCertificationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.FooterCertificationWhereInput | Prisma.FooterCertificationWhereInput[]
  OR?: Prisma.FooterCertificationWhereInput[]
  NOT?: Prisma.FooterCertificationWhereInput | Prisma.FooterCertificationWhereInput[]
  imageUrl?: Prisma.StringFilter<"FooterCertification"> | string
  isEnabled?: Prisma.BoolFilter<"FooterCertification"> | boolean
}, "id" | "name">

export type FooterCertificationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  _count?: Prisma.FooterCertificationCountOrderByAggregateInput
  _max?: Prisma.FooterCertificationMaxOrderByAggregateInput
  _min?: Prisma.FooterCertificationMinOrderByAggregateInput
}

export type FooterCertificationScalarWhereWithAggregatesInput = {
  AND?: Prisma.FooterCertificationScalarWhereWithAggregatesInput | Prisma.FooterCertificationScalarWhereWithAggregatesInput[]
  OR?: Prisma.FooterCertificationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FooterCertificationScalarWhereWithAggregatesInput | Prisma.FooterCertificationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FooterCertification"> | string
  name?: Prisma.StringWithAggregatesFilter<"FooterCertification"> | string
  imageUrl?: Prisma.StringWithAggregatesFilter<"FooterCertification"> | string
  isEnabled?: Prisma.BoolWithAggregatesFilter<"FooterCertification"> | boolean
}

export type FooterCertificationCreateInput = {
  id?: string
  name: string
  imageUrl: string
  isEnabled?: boolean
}

export type FooterCertificationUncheckedCreateInput = {
  id?: string
  name: string
  imageUrl: string
  isEnabled?: boolean
}

export type FooterCertificationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterCertificationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterCertificationCreateManyInput = {
  id?: string
  name: string
  imageUrl: string
  isEnabled?: boolean
}

export type FooterCertificationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterCertificationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterCertificationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterCertificationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterCertificationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}



export type FooterCertificationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerCertification"]>

export type FooterCertificationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerCertification"]>

export type FooterCertificationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerCertification"]>

export type FooterCertificationSelectScalar = {
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}

export type FooterCertificationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "imageUrl" | "isEnabled", ExtArgs["result"]["footerCertification"]>

export type $FooterCertificationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FooterCertification"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    imageUrl: string
    isEnabled: boolean
  }, ExtArgs["result"]["footerCertification"]>
  composites: {}
}

export type FooterCertificationGetPayload<S extends boolean | null | undefined | FooterCertificationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload, S>

export type FooterCertificationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FooterCertificationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FooterCertificationCountAggregateInputType | true
  }

export interface FooterCertificationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FooterCertification'], meta: { name: 'FooterCertification' } }
  /**
   * Find zero or one FooterCertification that matches the filter.
   * @param {FooterCertificationFindUniqueArgs} args - Arguments to find a FooterCertification
   * @example
   * // Get one FooterCertification
   * const footerCertification = await prisma.footerCertification.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FooterCertificationFindUniqueArgs>(args: Prisma.SelectSubset<T, FooterCertificationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FooterCertification that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FooterCertificationFindUniqueOrThrowArgs} args - Arguments to find a FooterCertification
   * @example
   * // Get one FooterCertification
   * const footerCertification = await prisma.footerCertification.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FooterCertificationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FooterCertificationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterCertification that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationFindFirstArgs} args - Arguments to find a FooterCertification
   * @example
   * // Get one FooterCertification
   * const footerCertification = await prisma.footerCertification.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FooterCertificationFindFirstArgs>(args?: Prisma.SelectSubset<T, FooterCertificationFindFirstArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterCertification that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationFindFirstOrThrowArgs} args - Arguments to find a FooterCertification
   * @example
   * // Get one FooterCertification
   * const footerCertification = await prisma.footerCertification.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FooterCertificationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FooterCertificationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FooterCertifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FooterCertifications
   * const footerCertifications = await prisma.footerCertification.findMany()
   * 
   * // Get first 10 FooterCertifications
   * const footerCertifications = await prisma.footerCertification.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const footerCertificationWithIdOnly = await prisma.footerCertification.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FooterCertificationFindManyArgs>(args?: Prisma.SelectSubset<T, FooterCertificationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FooterCertification.
   * @param {FooterCertificationCreateArgs} args - Arguments to create a FooterCertification.
   * @example
   * // Create one FooterCertification
   * const FooterCertification = await prisma.footerCertification.create({
   *   data: {
   *     // ... data to create a FooterCertification
   *   }
   * })
   * 
   */
  create<T extends FooterCertificationCreateArgs>(args: Prisma.SelectSubset<T, FooterCertificationCreateArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FooterCertifications.
   * @param {FooterCertificationCreateManyArgs} args - Arguments to create many FooterCertifications.
   * @example
   * // Create many FooterCertifications
   * const footerCertification = await prisma.footerCertification.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FooterCertificationCreateManyArgs>(args?: Prisma.SelectSubset<T, FooterCertificationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FooterCertifications and returns the data saved in the database.
   * @param {FooterCertificationCreateManyAndReturnArgs} args - Arguments to create many FooterCertifications.
   * @example
   * // Create many FooterCertifications
   * const footerCertification = await prisma.footerCertification.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FooterCertifications and only return the `id`
   * const footerCertificationWithIdOnly = await prisma.footerCertification.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FooterCertificationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FooterCertificationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FooterCertification.
   * @param {FooterCertificationDeleteArgs} args - Arguments to delete one FooterCertification.
   * @example
   * // Delete one FooterCertification
   * const FooterCertification = await prisma.footerCertification.delete({
   *   where: {
   *     // ... filter to delete one FooterCertification
   *   }
   * })
   * 
   */
  delete<T extends FooterCertificationDeleteArgs>(args: Prisma.SelectSubset<T, FooterCertificationDeleteArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FooterCertification.
   * @param {FooterCertificationUpdateArgs} args - Arguments to update one FooterCertification.
   * @example
   * // Update one FooterCertification
   * const footerCertification = await prisma.footerCertification.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FooterCertificationUpdateArgs>(args: Prisma.SelectSubset<T, FooterCertificationUpdateArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FooterCertifications.
   * @param {FooterCertificationDeleteManyArgs} args - Arguments to filter FooterCertifications to delete.
   * @example
   * // Delete a few FooterCertifications
   * const { count } = await prisma.footerCertification.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FooterCertificationDeleteManyArgs>(args?: Prisma.SelectSubset<T, FooterCertificationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterCertifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FooterCertifications
   * const footerCertification = await prisma.footerCertification.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FooterCertificationUpdateManyArgs>(args: Prisma.SelectSubset<T, FooterCertificationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterCertifications and returns the data updated in the database.
   * @param {FooterCertificationUpdateManyAndReturnArgs} args - Arguments to update many FooterCertifications.
   * @example
   * // Update many FooterCertifications
   * const footerCertification = await prisma.footerCertification.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FooterCertifications and only return the `id`
   * const footerCertificationWithIdOnly = await prisma.footerCertification.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FooterCertificationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FooterCertificationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FooterCertification.
   * @param {FooterCertificationUpsertArgs} args - Arguments to update or create a FooterCertification.
   * @example
   * // Update or create a FooterCertification
   * const footerCertification = await prisma.footerCertification.upsert({
   *   create: {
   *     // ... data to create a FooterCertification
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FooterCertification we want to update
   *   }
   * })
   */
  upsert<T extends FooterCertificationUpsertArgs>(args: Prisma.SelectSubset<T, FooterCertificationUpsertArgs<ExtArgs>>): Prisma.Prisma__FooterCertificationClient<runtime.Types.Result.GetResult<Prisma.$FooterCertificationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FooterCertifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationCountArgs} args - Arguments to filter FooterCertifications to count.
   * @example
   * // Count the number of FooterCertifications
   * const count = await prisma.footerCertification.count({
   *   where: {
   *     // ... the filter for the FooterCertifications we want to count
   *   }
   * })
  **/
  count<T extends FooterCertificationCountArgs>(
    args?: Prisma.Subset<T, FooterCertificationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FooterCertificationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FooterCertification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FooterCertificationAggregateArgs>(args: Prisma.Subset<T, FooterCertificationAggregateArgs>): Prisma.PrismaPromise<GetFooterCertificationAggregateType<T>>

  /**
   * Group by FooterCertification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCertificationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FooterCertificationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FooterCertificationGroupByArgs['orderBy'] }
      : { orderBy?: FooterCertificationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FooterCertificationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFooterCertificationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FooterCertification model
 */
readonly fields: FooterCertificationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FooterCertification.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FooterCertificationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FooterCertification model
 */
export interface FooterCertificationFieldRefs {
  readonly id: Prisma.FieldRef<"FooterCertification", 'String'>
  readonly name: Prisma.FieldRef<"FooterCertification", 'String'>
  readonly imageUrl: Prisma.FieldRef<"FooterCertification", 'String'>
  readonly isEnabled: Prisma.FieldRef<"FooterCertification", 'Boolean'>
}
    

// Custom InputTypes
/**
 * FooterCertification findUnique
 */
export type FooterCertificationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * Filter, which FooterCertification to fetch.
   */
  where: Prisma.FooterCertificationWhereUniqueInput
}

/**
 * FooterCertification findUniqueOrThrow
 */
export type FooterCertificationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * Filter, which FooterCertification to fetch.
   */
  where: Prisma.FooterCertificationWhereUniqueInput
}

/**
 * FooterCertification findFirst
 */
export type FooterCertificationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * Filter, which FooterCertification to fetch.
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterCertifications to fetch.
   */
  orderBy?: Prisma.FooterCertificationOrderByWithRelationInput | Prisma.FooterCertificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterCertifications.
   */
  cursor?: Prisma.FooterCertificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterCertifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterCertifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterCertifications.
   */
  distinct?: Prisma.FooterCertificationScalarFieldEnum | Prisma.FooterCertificationScalarFieldEnum[]
}

/**
 * FooterCertification findFirstOrThrow
 */
export type FooterCertificationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * Filter, which FooterCertification to fetch.
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterCertifications to fetch.
   */
  orderBy?: Prisma.FooterCertificationOrderByWithRelationInput | Prisma.FooterCertificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterCertifications.
   */
  cursor?: Prisma.FooterCertificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterCertifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterCertifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterCertifications.
   */
  distinct?: Prisma.FooterCertificationScalarFieldEnum | Prisma.FooterCertificationScalarFieldEnum[]
}

/**
 * FooterCertification findMany
 */
export type FooterCertificationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * Filter, which FooterCertifications to fetch.
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterCertifications to fetch.
   */
  orderBy?: Prisma.FooterCertificationOrderByWithRelationInput | Prisma.FooterCertificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FooterCertifications.
   */
  cursor?: Prisma.FooterCertificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterCertifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterCertifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterCertifications.
   */
  distinct?: Prisma.FooterCertificationScalarFieldEnum | Prisma.FooterCertificationScalarFieldEnum[]
}

/**
 * FooterCertification create
 */
export type FooterCertificationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * The data needed to create a FooterCertification.
   */
  data: Prisma.XOR<Prisma.FooterCertificationCreateInput, Prisma.FooterCertificationUncheckedCreateInput>
}

/**
 * FooterCertification createMany
 */
export type FooterCertificationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FooterCertifications.
   */
  data: Prisma.FooterCertificationCreateManyInput | Prisma.FooterCertificationCreateManyInput[]
}

/**
 * FooterCertification createManyAndReturn
 */
export type FooterCertificationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * The data used to create many FooterCertifications.
   */
  data: Prisma.FooterCertificationCreateManyInput | Prisma.FooterCertificationCreateManyInput[]
}

/**
 * FooterCertification update
 */
export type FooterCertificationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * The data needed to update a FooterCertification.
   */
  data: Prisma.XOR<Prisma.FooterCertificationUpdateInput, Prisma.FooterCertificationUncheckedUpdateInput>
  /**
   * Choose, which FooterCertification to update.
   */
  where: Prisma.FooterCertificationWhereUniqueInput
}

/**
 * FooterCertification updateMany
 */
export type FooterCertificationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FooterCertifications.
   */
  data: Prisma.XOR<Prisma.FooterCertificationUpdateManyMutationInput, Prisma.FooterCertificationUncheckedUpdateManyInput>
  /**
   * Filter which FooterCertifications to update
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * Limit how many FooterCertifications to update.
   */
  limit?: number
}

/**
 * FooterCertification updateManyAndReturn
 */
export type FooterCertificationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * The data used to update FooterCertifications.
   */
  data: Prisma.XOR<Prisma.FooterCertificationUpdateManyMutationInput, Prisma.FooterCertificationUncheckedUpdateManyInput>
  /**
   * Filter which FooterCertifications to update
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * Limit how many FooterCertifications to update.
   */
  limit?: number
}

/**
 * FooterCertification upsert
 */
export type FooterCertificationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * The filter to search for the FooterCertification to update in case it exists.
   */
  where: Prisma.FooterCertificationWhereUniqueInput
  /**
   * In case the FooterCertification found by the `where` argument doesn't exist, create a new FooterCertification with this data.
   */
  create: Prisma.XOR<Prisma.FooterCertificationCreateInput, Prisma.FooterCertificationUncheckedCreateInput>
  /**
   * In case the FooterCertification was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FooterCertificationUpdateInput, Prisma.FooterCertificationUncheckedUpdateInput>
}

/**
 * FooterCertification delete
 */
export type FooterCertificationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
  /**
   * Filter which FooterCertification to delete.
   */
  where: Prisma.FooterCertificationWhereUniqueInput
}

/**
 * FooterCertification deleteMany
 */
export type FooterCertificationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterCertifications to delete
   */
  where?: Prisma.FooterCertificationWhereInput
  /**
   * Limit how many FooterCertifications to delete.
   */
  limit?: number
}

/**
 * FooterCertification without action
 */
export type FooterCertificationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCertification
   */
  select?: Prisma.FooterCertificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterCertification
   */
  omit?: Prisma.FooterCertificationOmit<ExtArgs> | null
}
