
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FooterShippingPartner` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FooterShippingPartner
 * 
 */
export type FooterShippingPartnerModel = runtime.Types.Result.DefaultSelection<Prisma.$FooterShippingPartnerPayload>

export type AggregateFooterShippingPartner = {
  _count: FooterShippingPartnerCountAggregateOutputType | null
  _min: FooterShippingPartnerMinAggregateOutputType | null
  _max: FooterShippingPartnerMaxAggregateOutputType | null
}

export type FooterShippingPartnerMinAggregateOutputType = {
  id: string | null
  name: string | null
  imageUrl: string | null
  isEnabled: boolean | null
}

export type FooterShippingPartnerMaxAggregateOutputType = {
  id: string | null
  name: string | null
  imageUrl: string | null
  isEnabled: boolean | null
}

export type FooterShippingPartnerCountAggregateOutputType = {
  id: number
  name: number
  imageUrl: number
  isEnabled: number
  _all: number
}


export type FooterShippingPartnerMinAggregateInputType = {
  id?: true
  name?: true
  imageUrl?: true
  isEnabled?: true
}

export type FooterShippingPartnerMaxAggregateInputType = {
  id?: true
  name?: true
  imageUrl?: true
  isEnabled?: true
}

export type FooterShippingPartnerCountAggregateInputType = {
  id?: true
  name?: true
  imageUrl?: true
  isEnabled?: true
  _all?: true
}

export type FooterShippingPartnerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterShippingPartner to aggregate.
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterShippingPartners to fetch.
   */
  orderBy?: Prisma.FooterShippingPartnerOrderByWithRelationInput | Prisma.FooterShippingPartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FooterShippingPartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterShippingPartners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterShippingPartners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FooterShippingPartners
  **/
  _count?: true | FooterShippingPartnerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FooterShippingPartnerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FooterShippingPartnerMaxAggregateInputType
}

export type GetFooterShippingPartnerAggregateType<T extends FooterShippingPartnerAggregateArgs> = {
      [P in keyof T & keyof AggregateFooterShippingPartner]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFooterShippingPartner[P]>
    : Prisma.GetScalarType<T[P], AggregateFooterShippingPartner[P]>
}




export type FooterShippingPartnerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterShippingPartnerWhereInput
  orderBy?: Prisma.FooterShippingPartnerOrderByWithAggregationInput | Prisma.FooterShippingPartnerOrderByWithAggregationInput[]
  by: Prisma.FooterShippingPartnerScalarFieldEnum[] | Prisma.FooterShippingPartnerScalarFieldEnum
  having?: Prisma.FooterShippingPartnerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FooterShippingPartnerCountAggregateInputType | true
  _min?: FooterShippingPartnerMinAggregateInputType
  _max?: FooterShippingPartnerMaxAggregateInputType
}

export type FooterShippingPartnerGroupByOutputType = {
  id: string
  name: string
  imageUrl: string
  isEnabled: boolean
  _count: FooterShippingPartnerCountAggregateOutputType | null
  _min: FooterShippingPartnerMinAggregateOutputType | null
  _max: FooterShippingPartnerMaxAggregateOutputType | null
}

export type GetFooterShippingPartnerGroupByPayload<T extends FooterShippingPartnerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FooterShippingPartnerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FooterShippingPartnerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FooterShippingPartnerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FooterShippingPartnerGroupByOutputType[P]>
      }
    >
  >



export type FooterShippingPartnerWhereInput = {
  AND?: Prisma.FooterShippingPartnerWhereInput | Prisma.FooterShippingPartnerWhereInput[]
  OR?: Prisma.FooterShippingPartnerWhereInput[]
  NOT?: Prisma.FooterShippingPartnerWhereInput | Prisma.FooterShippingPartnerWhereInput[]
  id?: Prisma.StringFilter<"FooterShippingPartner"> | string
  name?: Prisma.StringFilter<"FooterShippingPartner"> | string
  imageUrl?: Prisma.StringFilter<"FooterShippingPartner"> | string
  isEnabled?: Prisma.BoolFilter<"FooterShippingPartner"> | boolean
}

export type FooterShippingPartnerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterShippingPartnerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.FooterShippingPartnerWhereInput | Prisma.FooterShippingPartnerWhereInput[]
  OR?: Prisma.FooterShippingPartnerWhereInput[]
  NOT?: Prisma.FooterShippingPartnerWhereInput | Prisma.FooterShippingPartnerWhereInput[]
  imageUrl?: Prisma.StringFilter<"FooterShippingPartner"> | string
  isEnabled?: Prisma.BoolFilter<"FooterShippingPartner"> | boolean
}, "id" | "name">

export type FooterShippingPartnerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  _count?: Prisma.FooterShippingPartnerCountOrderByAggregateInput
  _max?: Prisma.FooterShippingPartnerMaxOrderByAggregateInput
  _min?: Prisma.FooterShippingPartnerMinOrderByAggregateInput
}

export type FooterShippingPartnerScalarWhereWithAggregatesInput = {
  AND?: Prisma.FooterShippingPartnerScalarWhereWithAggregatesInput | Prisma.FooterShippingPartnerScalarWhereWithAggregatesInput[]
  OR?: Prisma.FooterShippingPartnerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FooterShippingPartnerScalarWhereWithAggregatesInput | Prisma.FooterShippingPartnerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FooterShippingPartner"> | string
  name?: Prisma.StringWithAggregatesFilter<"FooterShippingPartner"> | string
  imageUrl?: Prisma.StringWithAggregatesFilter<"FooterShippingPartner"> | string
  isEnabled?: Prisma.BoolWithAggregatesFilter<"FooterShippingPartner"> | boolean
}

export type FooterShippingPartnerCreateInput = {
  id?: string
  name: string
  imageUrl: string
  isEnabled?: boolean
}

export type FooterShippingPartnerUncheckedCreateInput = {
  id?: string
  name: string
  imageUrl: string
  isEnabled?: boolean
}

export type FooterShippingPartnerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterShippingPartnerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterShippingPartnerCreateManyInput = {
  id?: string
  name: string
  imageUrl: string
  isEnabled?: boolean
}

export type FooterShippingPartnerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterShippingPartnerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterShippingPartnerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterShippingPartnerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterShippingPartnerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}



export type FooterShippingPartnerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerShippingPartner"]>

export type FooterShippingPartnerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerShippingPartner"]>

export type FooterShippingPartnerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerShippingPartner"]>

export type FooterShippingPartnerSelectScalar = {
  id?: boolean
  name?: boolean
  imageUrl?: boolean
  isEnabled?: boolean
}

export type FooterShippingPartnerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "imageUrl" | "isEnabled", ExtArgs["result"]["footerShippingPartner"]>

export type $FooterShippingPartnerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FooterShippingPartner"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    imageUrl: string
    isEnabled: boolean
  }, ExtArgs["result"]["footerShippingPartner"]>
  composites: {}
}

export type FooterShippingPartnerGetPayload<S extends boolean | null | undefined | FooterShippingPartnerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload, S>

export type FooterShippingPartnerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FooterShippingPartnerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FooterShippingPartnerCountAggregateInputType | true
  }

export interface FooterShippingPartnerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FooterShippingPartner'], meta: { name: 'FooterShippingPartner' } }
  /**
   * Find zero or one FooterShippingPartner that matches the filter.
   * @param {FooterShippingPartnerFindUniqueArgs} args - Arguments to find a FooterShippingPartner
   * @example
   * // Get one FooterShippingPartner
   * const footerShippingPartner = await prisma.footerShippingPartner.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FooterShippingPartnerFindUniqueArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FooterShippingPartner that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FooterShippingPartnerFindUniqueOrThrowArgs} args - Arguments to find a FooterShippingPartner
   * @example
   * // Get one FooterShippingPartner
   * const footerShippingPartner = await prisma.footerShippingPartner.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FooterShippingPartnerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterShippingPartner that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerFindFirstArgs} args - Arguments to find a FooterShippingPartner
   * @example
   * // Get one FooterShippingPartner
   * const footerShippingPartner = await prisma.footerShippingPartner.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FooterShippingPartnerFindFirstArgs>(args?: Prisma.SelectSubset<T, FooterShippingPartnerFindFirstArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterShippingPartner that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerFindFirstOrThrowArgs} args - Arguments to find a FooterShippingPartner
   * @example
   * // Get one FooterShippingPartner
   * const footerShippingPartner = await prisma.footerShippingPartner.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FooterShippingPartnerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FooterShippingPartnerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FooterShippingPartners that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FooterShippingPartners
   * const footerShippingPartners = await prisma.footerShippingPartner.findMany()
   * 
   * // Get first 10 FooterShippingPartners
   * const footerShippingPartners = await prisma.footerShippingPartner.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const footerShippingPartnerWithIdOnly = await prisma.footerShippingPartner.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FooterShippingPartnerFindManyArgs>(args?: Prisma.SelectSubset<T, FooterShippingPartnerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FooterShippingPartner.
   * @param {FooterShippingPartnerCreateArgs} args - Arguments to create a FooterShippingPartner.
   * @example
   * // Create one FooterShippingPartner
   * const FooterShippingPartner = await prisma.footerShippingPartner.create({
   *   data: {
   *     // ... data to create a FooterShippingPartner
   *   }
   * })
   * 
   */
  create<T extends FooterShippingPartnerCreateArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerCreateArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FooterShippingPartners.
   * @param {FooterShippingPartnerCreateManyArgs} args - Arguments to create many FooterShippingPartners.
   * @example
   * // Create many FooterShippingPartners
   * const footerShippingPartner = await prisma.footerShippingPartner.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FooterShippingPartnerCreateManyArgs>(args?: Prisma.SelectSubset<T, FooterShippingPartnerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FooterShippingPartners and returns the data saved in the database.
   * @param {FooterShippingPartnerCreateManyAndReturnArgs} args - Arguments to create many FooterShippingPartners.
   * @example
   * // Create many FooterShippingPartners
   * const footerShippingPartner = await prisma.footerShippingPartner.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FooterShippingPartners and only return the `id`
   * const footerShippingPartnerWithIdOnly = await prisma.footerShippingPartner.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FooterShippingPartnerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FooterShippingPartnerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FooterShippingPartner.
   * @param {FooterShippingPartnerDeleteArgs} args - Arguments to delete one FooterShippingPartner.
   * @example
   * // Delete one FooterShippingPartner
   * const FooterShippingPartner = await prisma.footerShippingPartner.delete({
   *   where: {
   *     // ... filter to delete one FooterShippingPartner
   *   }
   * })
   * 
   */
  delete<T extends FooterShippingPartnerDeleteArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerDeleteArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FooterShippingPartner.
   * @param {FooterShippingPartnerUpdateArgs} args - Arguments to update one FooterShippingPartner.
   * @example
   * // Update one FooterShippingPartner
   * const footerShippingPartner = await prisma.footerShippingPartner.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FooterShippingPartnerUpdateArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerUpdateArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FooterShippingPartners.
   * @param {FooterShippingPartnerDeleteManyArgs} args - Arguments to filter FooterShippingPartners to delete.
   * @example
   * // Delete a few FooterShippingPartners
   * const { count } = await prisma.footerShippingPartner.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FooterShippingPartnerDeleteManyArgs>(args?: Prisma.SelectSubset<T, FooterShippingPartnerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterShippingPartners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FooterShippingPartners
   * const footerShippingPartner = await prisma.footerShippingPartner.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FooterShippingPartnerUpdateManyArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterShippingPartners and returns the data updated in the database.
   * @param {FooterShippingPartnerUpdateManyAndReturnArgs} args - Arguments to update many FooterShippingPartners.
   * @example
   * // Update many FooterShippingPartners
   * const footerShippingPartner = await prisma.footerShippingPartner.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FooterShippingPartners and only return the `id`
   * const footerShippingPartnerWithIdOnly = await prisma.footerShippingPartner.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FooterShippingPartnerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FooterShippingPartner.
   * @param {FooterShippingPartnerUpsertArgs} args - Arguments to update or create a FooterShippingPartner.
   * @example
   * // Update or create a FooterShippingPartner
   * const footerShippingPartner = await prisma.footerShippingPartner.upsert({
   *   create: {
   *     // ... data to create a FooterShippingPartner
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FooterShippingPartner we want to update
   *   }
   * })
   */
  upsert<T extends FooterShippingPartnerUpsertArgs>(args: Prisma.SelectSubset<T, FooterShippingPartnerUpsertArgs<ExtArgs>>): Prisma.Prisma__FooterShippingPartnerClient<runtime.Types.Result.GetResult<Prisma.$FooterShippingPartnerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FooterShippingPartners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerCountArgs} args - Arguments to filter FooterShippingPartners to count.
   * @example
   * // Count the number of FooterShippingPartners
   * const count = await prisma.footerShippingPartner.count({
   *   where: {
   *     // ... the filter for the FooterShippingPartners we want to count
   *   }
   * })
  **/
  count<T extends FooterShippingPartnerCountArgs>(
    args?: Prisma.Subset<T, FooterShippingPartnerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FooterShippingPartnerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FooterShippingPartner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FooterShippingPartnerAggregateArgs>(args: Prisma.Subset<T, FooterShippingPartnerAggregateArgs>): Prisma.PrismaPromise<GetFooterShippingPartnerAggregateType<T>>

  /**
   * Group by FooterShippingPartner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterShippingPartnerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FooterShippingPartnerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FooterShippingPartnerGroupByArgs['orderBy'] }
      : { orderBy?: FooterShippingPartnerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FooterShippingPartnerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFooterShippingPartnerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FooterShippingPartner model
 */
readonly fields: FooterShippingPartnerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FooterShippingPartner.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FooterShippingPartnerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FooterShippingPartner model
 */
export interface FooterShippingPartnerFieldRefs {
  readonly id: Prisma.FieldRef<"FooterShippingPartner", 'String'>
  readonly name: Prisma.FieldRef<"FooterShippingPartner", 'String'>
  readonly imageUrl: Prisma.FieldRef<"FooterShippingPartner", 'String'>
  readonly isEnabled: Prisma.FieldRef<"FooterShippingPartner", 'Boolean'>
}
    

// Custom InputTypes
/**
 * FooterShippingPartner findUnique
 */
export type FooterShippingPartnerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * Filter, which FooterShippingPartner to fetch.
   */
  where: Prisma.FooterShippingPartnerWhereUniqueInput
}

/**
 * FooterShippingPartner findUniqueOrThrow
 */
export type FooterShippingPartnerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * Filter, which FooterShippingPartner to fetch.
   */
  where: Prisma.FooterShippingPartnerWhereUniqueInput
}

/**
 * FooterShippingPartner findFirst
 */
export type FooterShippingPartnerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * Filter, which FooterShippingPartner to fetch.
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterShippingPartners to fetch.
   */
  orderBy?: Prisma.FooterShippingPartnerOrderByWithRelationInput | Prisma.FooterShippingPartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterShippingPartners.
   */
  cursor?: Prisma.FooterShippingPartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterShippingPartners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterShippingPartners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterShippingPartners.
   */
  distinct?: Prisma.FooterShippingPartnerScalarFieldEnum | Prisma.FooterShippingPartnerScalarFieldEnum[]
}

/**
 * FooterShippingPartner findFirstOrThrow
 */
export type FooterShippingPartnerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * Filter, which FooterShippingPartner to fetch.
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterShippingPartners to fetch.
   */
  orderBy?: Prisma.FooterShippingPartnerOrderByWithRelationInput | Prisma.FooterShippingPartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterShippingPartners.
   */
  cursor?: Prisma.FooterShippingPartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterShippingPartners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterShippingPartners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterShippingPartners.
   */
  distinct?: Prisma.FooterShippingPartnerScalarFieldEnum | Prisma.FooterShippingPartnerScalarFieldEnum[]
}

/**
 * FooterShippingPartner findMany
 */
export type FooterShippingPartnerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * Filter, which FooterShippingPartners to fetch.
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterShippingPartners to fetch.
   */
  orderBy?: Prisma.FooterShippingPartnerOrderByWithRelationInput | Prisma.FooterShippingPartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FooterShippingPartners.
   */
  cursor?: Prisma.FooterShippingPartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterShippingPartners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterShippingPartners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterShippingPartners.
   */
  distinct?: Prisma.FooterShippingPartnerScalarFieldEnum | Prisma.FooterShippingPartnerScalarFieldEnum[]
}

/**
 * FooterShippingPartner create
 */
export type FooterShippingPartnerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * The data needed to create a FooterShippingPartner.
   */
  data: Prisma.XOR<Prisma.FooterShippingPartnerCreateInput, Prisma.FooterShippingPartnerUncheckedCreateInput>
}

/**
 * FooterShippingPartner createMany
 */
export type FooterShippingPartnerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FooterShippingPartners.
   */
  data: Prisma.FooterShippingPartnerCreateManyInput | Prisma.FooterShippingPartnerCreateManyInput[]
}

/**
 * FooterShippingPartner createManyAndReturn
 */
export type FooterShippingPartnerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * The data used to create many FooterShippingPartners.
   */
  data: Prisma.FooterShippingPartnerCreateManyInput | Prisma.FooterShippingPartnerCreateManyInput[]
}

/**
 * FooterShippingPartner update
 */
export type FooterShippingPartnerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * The data needed to update a FooterShippingPartner.
   */
  data: Prisma.XOR<Prisma.FooterShippingPartnerUpdateInput, Prisma.FooterShippingPartnerUncheckedUpdateInput>
  /**
   * Choose, which FooterShippingPartner to update.
   */
  where: Prisma.FooterShippingPartnerWhereUniqueInput
}

/**
 * FooterShippingPartner updateMany
 */
export type FooterShippingPartnerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FooterShippingPartners.
   */
  data: Prisma.XOR<Prisma.FooterShippingPartnerUpdateManyMutationInput, Prisma.FooterShippingPartnerUncheckedUpdateManyInput>
  /**
   * Filter which FooterShippingPartners to update
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * Limit how many FooterShippingPartners to update.
   */
  limit?: number
}

/**
 * FooterShippingPartner updateManyAndReturn
 */
export type FooterShippingPartnerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * The data used to update FooterShippingPartners.
   */
  data: Prisma.XOR<Prisma.FooterShippingPartnerUpdateManyMutationInput, Prisma.FooterShippingPartnerUncheckedUpdateManyInput>
  /**
   * Filter which FooterShippingPartners to update
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * Limit how many FooterShippingPartners to update.
   */
  limit?: number
}

/**
 * FooterShippingPartner upsert
 */
export type FooterShippingPartnerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * The filter to search for the FooterShippingPartner to update in case it exists.
   */
  where: Prisma.FooterShippingPartnerWhereUniqueInput
  /**
   * In case the FooterShippingPartner found by the `where` argument doesn't exist, create a new FooterShippingPartner with this data.
   */
  create: Prisma.XOR<Prisma.FooterShippingPartnerCreateInput, Prisma.FooterShippingPartnerUncheckedCreateInput>
  /**
   * In case the FooterShippingPartner was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FooterShippingPartnerUpdateInput, Prisma.FooterShippingPartnerUncheckedUpdateInput>
}

/**
 * FooterShippingPartner delete
 */
export type FooterShippingPartnerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
  /**
   * Filter which FooterShippingPartner to delete.
   */
  where: Prisma.FooterShippingPartnerWhereUniqueInput
}

/**
 * FooterShippingPartner deleteMany
 */
export type FooterShippingPartnerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterShippingPartners to delete
   */
  where?: Prisma.FooterShippingPartnerWhereInput
  /**
   * Limit how many FooterShippingPartners to delete.
   */
  limit?: number
}

/**
 * FooterShippingPartner without action
 */
export type FooterShippingPartnerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterShippingPartner
   */
  select?: Prisma.FooterShippingPartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterShippingPartner
   */
  omit?: Prisma.FooterShippingPartnerOmit<ExtArgs> | null
}
