
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FooterLanguage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FooterLanguage
 * 
 */
export type FooterLanguageModel = runtime.Types.Result.DefaultSelection<Prisma.$FooterLanguagePayload>

export type AggregateFooterLanguage = {
  _count: FooterLanguageCountAggregateOutputType | null
  _min: FooterLanguageMinAggregateOutputType | null
  _max: FooterLanguageMaxAggregateOutputType | null
}

export type FooterLanguageMinAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  isEnabled: boolean | null
}

export type FooterLanguageMaxAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  isEnabled: boolean | null
}

export type FooterLanguageCountAggregateOutputType = {
  id: number
  code: number
  name: number
  isEnabled: number
  _all: number
}


export type FooterLanguageMinAggregateInputType = {
  id?: true
  code?: true
  name?: true
  isEnabled?: true
}

export type FooterLanguageMaxAggregateInputType = {
  id?: true
  code?: true
  name?: true
  isEnabled?: true
}

export type FooterLanguageCountAggregateInputType = {
  id?: true
  code?: true
  name?: true
  isEnabled?: true
  _all?: true
}

export type FooterLanguageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterLanguage to aggregate.
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterLanguages to fetch.
   */
  orderBy?: Prisma.FooterLanguageOrderByWithRelationInput | Prisma.FooterLanguageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FooterLanguageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterLanguages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterLanguages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FooterLanguages
  **/
  _count?: true | FooterLanguageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FooterLanguageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FooterLanguageMaxAggregateInputType
}

export type GetFooterLanguageAggregateType<T extends FooterLanguageAggregateArgs> = {
      [P in keyof T & keyof AggregateFooterLanguage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFooterLanguage[P]>
    : Prisma.GetScalarType<T[P], AggregateFooterLanguage[P]>
}




export type FooterLanguageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterLanguageWhereInput
  orderBy?: Prisma.FooterLanguageOrderByWithAggregationInput | Prisma.FooterLanguageOrderByWithAggregationInput[]
  by: Prisma.FooterLanguageScalarFieldEnum[] | Prisma.FooterLanguageScalarFieldEnum
  having?: Prisma.FooterLanguageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FooterLanguageCountAggregateInputType | true
  _min?: FooterLanguageMinAggregateInputType
  _max?: FooterLanguageMaxAggregateInputType
}

export type FooterLanguageGroupByOutputType = {
  id: string
  code: string
  name: string
  isEnabled: boolean
  _count: FooterLanguageCountAggregateOutputType | null
  _min: FooterLanguageMinAggregateOutputType | null
  _max: FooterLanguageMaxAggregateOutputType | null
}

export type GetFooterLanguageGroupByPayload<T extends FooterLanguageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FooterLanguageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FooterLanguageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FooterLanguageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FooterLanguageGroupByOutputType[P]>
      }
    >
  >



export type FooterLanguageWhereInput = {
  AND?: Prisma.FooterLanguageWhereInput | Prisma.FooterLanguageWhereInput[]
  OR?: Prisma.FooterLanguageWhereInput[]
  NOT?: Prisma.FooterLanguageWhereInput | Prisma.FooterLanguageWhereInput[]
  id?: Prisma.StringFilter<"FooterLanguage"> | string
  code?: Prisma.StringFilter<"FooterLanguage"> | string
  name?: Prisma.StringFilter<"FooterLanguage"> | string
  isEnabled?: Prisma.BoolFilter<"FooterLanguage"> | boolean
}

export type FooterLanguageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterLanguageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.FooterLanguageWhereInput | Prisma.FooterLanguageWhereInput[]
  OR?: Prisma.FooterLanguageWhereInput[]
  NOT?: Prisma.FooterLanguageWhereInput | Prisma.FooterLanguageWhereInput[]
  name?: Prisma.StringFilter<"FooterLanguage"> | string
  isEnabled?: Prisma.BoolFilter<"FooterLanguage"> | boolean
}, "id" | "code">

export type FooterLanguageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  _count?: Prisma.FooterLanguageCountOrderByAggregateInput
  _max?: Prisma.FooterLanguageMaxOrderByAggregateInput
  _min?: Prisma.FooterLanguageMinOrderByAggregateInput
}

export type FooterLanguageScalarWhereWithAggregatesInput = {
  AND?: Prisma.FooterLanguageScalarWhereWithAggregatesInput | Prisma.FooterLanguageScalarWhereWithAggregatesInput[]
  OR?: Prisma.FooterLanguageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FooterLanguageScalarWhereWithAggregatesInput | Prisma.FooterLanguageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FooterLanguage"> | string
  code?: Prisma.StringWithAggregatesFilter<"FooterLanguage"> | string
  name?: Prisma.StringWithAggregatesFilter<"FooterLanguage"> | string
  isEnabled?: Prisma.BoolWithAggregatesFilter<"FooterLanguage"> | boolean
}

export type FooterLanguageCreateInput = {
  id?: string
  code: string
  name: string
  isEnabled?: boolean
}

export type FooterLanguageUncheckedCreateInput = {
  id?: string
  code: string
  name: string
  isEnabled?: boolean
}

export type FooterLanguageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterLanguageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterLanguageCreateManyInput = {
  id?: string
  code: string
  name: string
  isEnabled?: boolean
}

export type FooterLanguageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterLanguageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type FooterLanguageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterLanguageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}

export type FooterLanguageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
}



export type FooterLanguageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerLanguage"]>

export type FooterLanguageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerLanguage"]>

export type FooterLanguageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  isEnabled?: boolean
}, ExtArgs["result"]["footerLanguage"]>

export type FooterLanguageSelectScalar = {
  id?: boolean
  code?: boolean
  name?: boolean
  isEnabled?: boolean
}

export type FooterLanguageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "name" | "isEnabled", ExtArgs["result"]["footerLanguage"]>

export type $FooterLanguagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FooterLanguage"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    name: string
    isEnabled: boolean
  }, ExtArgs["result"]["footerLanguage"]>
  composites: {}
}

export type FooterLanguageGetPayload<S extends boolean | null | undefined | FooterLanguageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload, S>

export type FooterLanguageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FooterLanguageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FooterLanguageCountAggregateInputType | true
  }

export interface FooterLanguageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FooterLanguage'], meta: { name: 'FooterLanguage' } }
  /**
   * Find zero or one FooterLanguage that matches the filter.
   * @param {FooterLanguageFindUniqueArgs} args - Arguments to find a FooterLanguage
   * @example
   * // Get one FooterLanguage
   * const footerLanguage = await prisma.footerLanguage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FooterLanguageFindUniqueArgs>(args: Prisma.SelectSubset<T, FooterLanguageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FooterLanguage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FooterLanguageFindUniqueOrThrowArgs} args - Arguments to find a FooterLanguage
   * @example
   * // Get one FooterLanguage
   * const footerLanguage = await prisma.footerLanguage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FooterLanguageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FooterLanguageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterLanguage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageFindFirstArgs} args - Arguments to find a FooterLanguage
   * @example
   * // Get one FooterLanguage
   * const footerLanguage = await prisma.footerLanguage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FooterLanguageFindFirstArgs>(args?: Prisma.SelectSubset<T, FooterLanguageFindFirstArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterLanguage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageFindFirstOrThrowArgs} args - Arguments to find a FooterLanguage
   * @example
   * // Get one FooterLanguage
   * const footerLanguage = await prisma.footerLanguage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FooterLanguageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FooterLanguageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FooterLanguages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FooterLanguages
   * const footerLanguages = await prisma.footerLanguage.findMany()
   * 
   * // Get first 10 FooterLanguages
   * const footerLanguages = await prisma.footerLanguage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const footerLanguageWithIdOnly = await prisma.footerLanguage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FooterLanguageFindManyArgs>(args?: Prisma.SelectSubset<T, FooterLanguageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FooterLanguage.
   * @param {FooterLanguageCreateArgs} args - Arguments to create a FooterLanguage.
   * @example
   * // Create one FooterLanguage
   * const FooterLanguage = await prisma.footerLanguage.create({
   *   data: {
   *     // ... data to create a FooterLanguage
   *   }
   * })
   * 
   */
  create<T extends FooterLanguageCreateArgs>(args: Prisma.SelectSubset<T, FooterLanguageCreateArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FooterLanguages.
   * @param {FooterLanguageCreateManyArgs} args - Arguments to create many FooterLanguages.
   * @example
   * // Create many FooterLanguages
   * const footerLanguage = await prisma.footerLanguage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FooterLanguageCreateManyArgs>(args?: Prisma.SelectSubset<T, FooterLanguageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FooterLanguages and returns the data saved in the database.
   * @param {FooterLanguageCreateManyAndReturnArgs} args - Arguments to create many FooterLanguages.
   * @example
   * // Create many FooterLanguages
   * const footerLanguage = await prisma.footerLanguage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FooterLanguages and only return the `id`
   * const footerLanguageWithIdOnly = await prisma.footerLanguage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FooterLanguageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FooterLanguageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FooterLanguage.
   * @param {FooterLanguageDeleteArgs} args - Arguments to delete one FooterLanguage.
   * @example
   * // Delete one FooterLanguage
   * const FooterLanguage = await prisma.footerLanguage.delete({
   *   where: {
   *     // ... filter to delete one FooterLanguage
   *   }
   * })
   * 
   */
  delete<T extends FooterLanguageDeleteArgs>(args: Prisma.SelectSubset<T, FooterLanguageDeleteArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FooterLanguage.
   * @param {FooterLanguageUpdateArgs} args - Arguments to update one FooterLanguage.
   * @example
   * // Update one FooterLanguage
   * const footerLanguage = await prisma.footerLanguage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FooterLanguageUpdateArgs>(args: Prisma.SelectSubset<T, FooterLanguageUpdateArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FooterLanguages.
   * @param {FooterLanguageDeleteManyArgs} args - Arguments to filter FooterLanguages to delete.
   * @example
   * // Delete a few FooterLanguages
   * const { count } = await prisma.footerLanguage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FooterLanguageDeleteManyArgs>(args?: Prisma.SelectSubset<T, FooterLanguageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterLanguages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FooterLanguages
   * const footerLanguage = await prisma.footerLanguage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FooterLanguageUpdateManyArgs>(args: Prisma.SelectSubset<T, FooterLanguageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterLanguages and returns the data updated in the database.
   * @param {FooterLanguageUpdateManyAndReturnArgs} args - Arguments to update many FooterLanguages.
   * @example
   * // Update many FooterLanguages
   * const footerLanguage = await prisma.footerLanguage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FooterLanguages and only return the `id`
   * const footerLanguageWithIdOnly = await prisma.footerLanguage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FooterLanguageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FooterLanguageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FooterLanguage.
   * @param {FooterLanguageUpsertArgs} args - Arguments to update or create a FooterLanguage.
   * @example
   * // Update or create a FooterLanguage
   * const footerLanguage = await prisma.footerLanguage.upsert({
   *   create: {
   *     // ... data to create a FooterLanguage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FooterLanguage we want to update
   *   }
   * })
   */
  upsert<T extends FooterLanguageUpsertArgs>(args: Prisma.SelectSubset<T, FooterLanguageUpsertArgs<ExtArgs>>): Prisma.Prisma__FooterLanguageClient<runtime.Types.Result.GetResult<Prisma.$FooterLanguagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FooterLanguages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageCountArgs} args - Arguments to filter FooterLanguages to count.
   * @example
   * // Count the number of FooterLanguages
   * const count = await prisma.footerLanguage.count({
   *   where: {
   *     // ... the filter for the FooterLanguages we want to count
   *   }
   * })
  **/
  count<T extends FooterLanguageCountArgs>(
    args?: Prisma.Subset<T, FooterLanguageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FooterLanguageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FooterLanguage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FooterLanguageAggregateArgs>(args: Prisma.Subset<T, FooterLanguageAggregateArgs>): Prisma.PrismaPromise<GetFooterLanguageAggregateType<T>>

  /**
   * Group by FooterLanguage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterLanguageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FooterLanguageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FooterLanguageGroupByArgs['orderBy'] }
      : { orderBy?: FooterLanguageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FooterLanguageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFooterLanguageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FooterLanguage model
 */
readonly fields: FooterLanguageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FooterLanguage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FooterLanguageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FooterLanguage model
 */
export interface FooterLanguageFieldRefs {
  readonly id: Prisma.FieldRef<"FooterLanguage", 'String'>
  readonly code: Prisma.FieldRef<"FooterLanguage", 'String'>
  readonly name: Prisma.FieldRef<"FooterLanguage", 'String'>
  readonly isEnabled: Prisma.FieldRef<"FooterLanguage", 'Boolean'>
}
    

// Custom InputTypes
/**
 * FooterLanguage findUnique
 */
export type FooterLanguageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * Filter, which FooterLanguage to fetch.
   */
  where: Prisma.FooterLanguageWhereUniqueInput
}

/**
 * FooterLanguage findUniqueOrThrow
 */
export type FooterLanguageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * Filter, which FooterLanguage to fetch.
   */
  where: Prisma.FooterLanguageWhereUniqueInput
}

/**
 * FooterLanguage findFirst
 */
export type FooterLanguageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * Filter, which FooterLanguage to fetch.
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterLanguages to fetch.
   */
  orderBy?: Prisma.FooterLanguageOrderByWithRelationInput | Prisma.FooterLanguageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterLanguages.
   */
  cursor?: Prisma.FooterLanguageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterLanguages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterLanguages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterLanguages.
   */
  distinct?: Prisma.FooterLanguageScalarFieldEnum | Prisma.FooterLanguageScalarFieldEnum[]
}

/**
 * FooterLanguage findFirstOrThrow
 */
export type FooterLanguageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * Filter, which FooterLanguage to fetch.
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterLanguages to fetch.
   */
  orderBy?: Prisma.FooterLanguageOrderByWithRelationInput | Prisma.FooterLanguageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterLanguages.
   */
  cursor?: Prisma.FooterLanguageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterLanguages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterLanguages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterLanguages.
   */
  distinct?: Prisma.FooterLanguageScalarFieldEnum | Prisma.FooterLanguageScalarFieldEnum[]
}

/**
 * FooterLanguage findMany
 */
export type FooterLanguageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * Filter, which FooterLanguages to fetch.
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterLanguages to fetch.
   */
  orderBy?: Prisma.FooterLanguageOrderByWithRelationInput | Prisma.FooterLanguageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FooterLanguages.
   */
  cursor?: Prisma.FooterLanguageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterLanguages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterLanguages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterLanguages.
   */
  distinct?: Prisma.FooterLanguageScalarFieldEnum | Prisma.FooterLanguageScalarFieldEnum[]
}

/**
 * FooterLanguage create
 */
export type FooterLanguageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * The data needed to create a FooterLanguage.
   */
  data: Prisma.XOR<Prisma.FooterLanguageCreateInput, Prisma.FooterLanguageUncheckedCreateInput>
}

/**
 * FooterLanguage createMany
 */
export type FooterLanguageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FooterLanguages.
   */
  data: Prisma.FooterLanguageCreateManyInput | Prisma.FooterLanguageCreateManyInput[]
}

/**
 * FooterLanguage createManyAndReturn
 */
export type FooterLanguageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * The data used to create many FooterLanguages.
   */
  data: Prisma.FooterLanguageCreateManyInput | Prisma.FooterLanguageCreateManyInput[]
}

/**
 * FooterLanguage update
 */
export type FooterLanguageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * The data needed to update a FooterLanguage.
   */
  data: Prisma.XOR<Prisma.FooterLanguageUpdateInput, Prisma.FooterLanguageUncheckedUpdateInput>
  /**
   * Choose, which FooterLanguage to update.
   */
  where: Prisma.FooterLanguageWhereUniqueInput
}

/**
 * FooterLanguage updateMany
 */
export type FooterLanguageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FooterLanguages.
   */
  data: Prisma.XOR<Prisma.FooterLanguageUpdateManyMutationInput, Prisma.FooterLanguageUncheckedUpdateManyInput>
  /**
   * Filter which FooterLanguages to update
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * Limit how many FooterLanguages to update.
   */
  limit?: number
}

/**
 * FooterLanguage updateManyAndReturn
 */
export type FooterLanguageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * The data used to update FooterLanguages.
   */
  data: Prisma.XOR<Prisma.FooterLanguageUpdateManyMutationInput, Prisma.FooterLanguageUncheckedUpdateManyInput>
  /**
   * Filter which FooterLanguages to update
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * Limit how many FooterLanguages to update.
   */
  limit?: number
}

/**
 * FooterLanguage upsert
 */
export type FooterLanguageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * The filter to search for the FooterLanguage to update in case it exists.
   */
  where: Prisma.FooterLanguageWhereUniqueInput
  /**
   * In case the FooterLanguage found by the `where` argument doesn't exist, create a new FooterLanguage with this data.
   */
  create: Prisma.XOR<Prisma.FooterLanguageCreateInput, Prisma.FooterLanguageUncheckedCreateInput>
  /**
   * In case the FooterLanguage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FooterLanguageUpdateInput, Prisma.FooterLanguageUncheckedUpdateInput>
}

/**
 * FooterLanguage delete
 */
export type FooterLanguageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
  /**
   * Filter which FooterLanguage to delete.
   */
  where: Prisma.FooterLanguageWhereUniqueInput
}

/**
 * FooterLanguage deleteMany
 */
export type FooterLanguageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterLanguages to delete
   */
  where?: Prisma.FooterLanguageWhereInput
  /**
   * Limit how many FooterLanguages to delete.
   */
  limit?: number
}

/**
 * FooterLanguage without action
 */
export type FooterLanguageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterLanguage
   */
  select?: Prisma.FooterLanguageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterLanguage
   */
  omit?: Prisma.FooterLanguageOmit<ExtArgs> | null
}
