
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VendorBankAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VendorBankAccount
 * 
 */
export type VendorBankAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$VendorBankAccountPayload>

export type AggregateVendorBankAccount = {
  _count: VendorBankAccountCountAggregateOutputType | null
  _min: VendorBankAccountMinAggregateOutputType | null
  _max: VendorBankAccountMaxAggregateOutputType | null
}

export type VendorBankAccountMinAggregateOutputType = {
  id: string | null
  vendorId: string | null
  bankName: string | null
  accountNumber: string | null
  accountHolder: string | null
  ifscCode: string | null
  cancelledChequeUrl: string | null
}

export type VendorBankAccountMaxAggregateOutputType = {
  id: string | null
  vendorId: string | null
  bankName: string | null
  accountNumber: string | null
  accountHolder: string | null
  ifscCode: string | null
  cancelledChequeUrl: string | null
}

export type VendorBankAccountCountAggregateOutputType = {
  id: number
  vendorId: number
  bankName: number
  accountNumber: number
  accountHolder: number
  ifscCode: number
  cancelledChequeUrl: number
  _all: number
}


export type VendorBankAccountMinAggregateInputType = {
  id?: true
  vendorId?: true
  bankName?: true
  accountNumber?: true
  accountHolder?: true
  ifscCode?: true
  cancelledChequeUrl?: true
}

export type VendorBankAccountMaxAggregateInputType = {
  id?: true
  vendorId?: true
  bankName?: true
  accountNumber?: true
  accountHolder?: true
  ifscCode?: true
  cancelledChequeUrl?: true
}

export type VendorBankAccountCountAggregateInputType = {
  id?: true
  vendorId?: true
  bankName?: true
  accountNumber?: true
  accountHolder?: true
  ifscCode?: true
  cancelledChequeUrl?: true
  _all?: true
}

export type VendorBankAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VendorBankAccount to aggregate.
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VendorBankAccounts to fetch.
   */
  orderBy?: Prisma.VendorBankAccountOrderByWithRelationInput | Prisma.VendorBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VendorBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VendorBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VendorBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VendorBankAccounts
  **/
  _count?: true | VendorBankAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VendorBankAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VendorBankAccountMaxAggregateInputType
}

export type GetVendorBankAccountAggregateType<T extends VendorBankAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateVendorBankAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVendorBankAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateVendorBankAccount[P]>
}




export type VendorBankAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VendorBankAccountWhereInput
  orderBy?: Prisma.VendorBankAccountOrderByWithAggregationInput | Prisma.VendorBankAccountOrderByWithAggregationInput[]
  by: Prisma.VendorBankAccountScalarFieldEnum[] | Prisma.VendorBankAccountScalarFieldEnum
  having?: Prisma.VendorBankAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VendorBankAccountCountAggregateInputType | true
  _min?: VendorBankAccountMinAggregateInputType
  _max?: VendorBankAccountMaxAggregateInputType
}

export type VendorBankAccountGroupByOutputType = {
  id: string
  vendorId: string
  bankName: string
  accountNumber: string
  accountHolder: string
  ifscCode: string
  cancelledChequeUrl: string
  _count: VendorBankAccountCountAggregateOutputType | null
  _min: VendorBankAccountMinAggregateOutputType | null
  _max: VendorBankAccountMaxAggregateOutputType | null
}

export type GetVendorBankAccountGroupByPayload<T extends VendorBankAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VendorBankAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VendorBankAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VendorBankAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VendorBankAccountGroupByOutputType[P]>
      }
    >
  >



export type VendorBankAccountWhereInput = {
  AND?: Prisma.VendorBankAccountWhereInput | Prisma.VendorBankAccountWhereInput[]
  OR?: Prisma.VendorBankAccountWhereInput[]
  NOT?: Prisma.VendorBankAccountWhereInput | Prisma.VendorBankAccountWhereInput[]
  id?: Prisma.StringFilter<"VendorBankAccount"> | string
  vendorId?: Prisma.StringFilter<"VendorBankAccount"> | string
  bankName?: Prisma.StringFilter<"VendorBankAccount"> | string
  accountNumber?: Prisma.StringFilter<"VendorBankAccount"> | string
  accountHolder?: Prisma.StringFilter<"VendorBankAccount"> | string
  ifscCode?: Prisma.StringFilter<"VendorBankAccount"> | string
  cancelledChequeUrl?: Prisma.StringFilter<"VendorBankAccount"> | string
  vendor?: Prisma.XOR<Prisma.VendorScalarRelationFilter, Prisma.VendorWhereInput>
}

export type VendorBankAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  accountHolder?: Prisma.SortOrder
  ifscCode?: Prisma.SortOrder
  cancelledChequeUrl?: Prisma.SortOrder
  vendor?: Prisma.VendorOrderByWithRelationInput
}

export type VendorBankAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  vendorId?: string
  AND?: Prisma.VendorBankAccountWhereInput | Prisma.VendorBankAccountWhereInput[]
  OR?: Prisma.VendorBankAccountWhereInput[]
  NOT?: Prisma.VendorBankAccountWhereInput | Prisma.VendorBankAccountWhereInput[]
  bankName?: Prisma.StringFilter<"VendorBankAccount"> | string
  accountNumber?: Prisma.StringFilter<"VendorBankAccount"> | string
  accountHolder?: Prisma.StringFilter<"VendorBankAccount"> | string
  ifscCode?: Prisma.StringFilter<"VendorBankAccount"> | string
  cancelledChequeUrl?: Prisma.StringFilter<"VendorBankAccount"> | string
  vendor?: Prisma.XOR<Prisma.VendorScalarRelationFilter, Prisma.VendorWhereInput>
}, "id" | "vendorId">

export type VendorBankAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  accountHolder?: Prisma.SortOrder
  ifscCode?: Prisma.SortOrder
  cancelledChequeUrl?: Prisma.SortOrder
  _count?: Prisma.VendorBankAccountCountOrderByAggregateInput
  _max?: Prisma.VendorBankAccountMaxOrderByAggregateInput
  _min?: Prisma.VendorBankAccountMinOrderByAggregateInput
}

export type VendorBankAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.VendorBankAccountScalarWhereWithAggregatesInput | Prisma.VendorBankAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.VendorBankAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VendorBankAccountScalarWhereWithAggregatesInput | Prisma.VendorBankAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
  vendorId?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
  bankName?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
  accountNumber?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
  accountHolder?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
  ifscCode?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
  cancelledChequeUrl?: Prisma.StringWithAggregatesFilter<"VendorBankAccount"> | string
}

export type VendorBankAccountCreateInput = {
  id?: string
  bankName: string
  accountNumber: string
  accountHolder: string
  ifscCode: string
  cancelledChequeUrl: string
  vendor: Prisma.VendorCreateNestedOneWithoutBankAccountInput
}

export type VendorBankAccountUncheckedCreateInput = {
  id?: string
  vendorId: string
  bankName: string
  accountNumber: string
  accountHolder: string
  ifscCode: string
  cancelledChequeUrl: string
}

export type VendorBankAccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  accountHolder?: Prisma.StringFieldUpdateOperationsInput | string
  ifscCode?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledChequeUrl?: Prisma.StringFieldUpdateOperationsInput | string
  vendor?: Prisma.VendorUpdateOneRequiredWithoutBankAccountNestedInput
}

export type VendorBankAccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vendorId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  accountHolder?: Prisma.StringFieldUpdateOperationsInput | string
  ifscCode?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledChequeUrl?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VendorBankAccountCreateManyInput = {
  id?: string
  vendorId: string
  bankName: string
  accountNumber: string
  accountHolder: string
  ifscCode: string
  cancelledChequeUrl: string
}

export type VendorBankAccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  accountHolder?: Prisma.StringFieldUpdateOperationsInput | string
  ifscCode?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledChequeUrl?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VendorBankAccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vendorId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  accountHolder?: Prisma.StringFieldUpdateOperationsInput | string
  ifscCode?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledChequeUrl?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VendorBankAccountNullableScalarRelationFilter = {
  is?: Prisma.VendorBankAccountWhereInput | null
  isNot?: Prisma.VendorBankAccountWhereInput | null
}

export type VendorBankAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  accountHolder?: Prisma.SortOrder
  ifscCode?: Prisma.SortOrder
  cancelledChequeUrl?: Prisma.SortOrder
}

export type VendorBankAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  accountHolder?: Prisma.SortOrder
  ifscCode?: Prisma.SortOrder
  cancelledChequeUrl?: Prisma.SortOrder
}

export type VendorBankAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  accountHolder?: Prisma.SortOrder
  ifscCode?: Prisma.SortOrder
  cancelledChequeUrl?: Prisma.SortOrder
}

export type VendorBankAccountCreateNestedOneWithoutVendorInput = {
  create?: Prisma.XOR<Prisma.VendorBankAccountCreateWithoutVendorInput, Prisma.VendorBankAccountUncheckedCreateWithoutVendorInput>
  connectOrCreate?: Prisma.VendorBankAccountCreateOrConnectWithoutVendorInput
  connect?: Prisma.VendorBankAccountWhereUniqueInput
}

export type VendorBankAccountUncheckedCreateNestedOneWithoutVendorInput = {
  create?: Prisma.XOR<Prisma.VendorBankAccountCreateWithoutVendorInput, Prisma.VendorBankAccountUncheckedCreateWithoutVendorInput>
  connectOrCreate?: Prisma.VendorBankAccountCreateOrConnectWithoutVendorInput
  connect?: Prisma.VendorBankAccountWhereUniqueInput
}

export type VendorBankAccountUpdateOneWithoutVendorNestedInput = {
  create?: Prisma.XOR<Prisma.VendorBankAccountCreateWithoutVendorInput, Prisma.VendorBankAccountUncheckedCreateWithoutVendorInput>
  connectOrCreate?: Prisma.VendorBankAccountCreateOrConnectWithoutVendorInput
  upsert?: Prisma.VendorBankAccountUpsertWithoutVendorInput
  disconnect?: Prisma.VendorBankAccountWhereInput | boolean
  delete?: Prisma.VendorBankAccountWhereInput | boolean
  connect?: Prisma.VendorBankAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VendorBankAccountUpdateToOneWithWhereWithoutVendorInput, Prisma.VendorBankAccountUpdateWithoutVendorInput>, Prisma.VendorBankAccountUncheckedUpdateWithoutVendorInput>
}

export type VendorBankAccountUncheckedUpdateOneWithoutVendorNestedInput = {
  create?: Prisma.XOR<Prisma.VendorBankAccountCreateWithoutVendorInput, Prisma.VendorBankAccountUncheckedCreateWithoutVendorInput>
  connectOrCreate?: Prisma.VendorBankAccountCreateOrConnectWithoutVendorInput
  upsert?: Prisma.VendorBankAccountUpsertWithoutVendorInput
  disconnect?: Prisma.VendorBankAccountWhereInput | boolean
  delete?: Prisma.VendorBankAccountWhereInput | boolean
  connect?: Prisma.VendorBankAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VendorBankAccountUpdateToOneWithWhereWithoutVendorInput, Prisma.VendorBankAccountUpdateWithoutVendorInput>, Prisma.VendorBankAccountUncheckedUpdateWithoutVendorInput>
}

export type VendorBankAccountCreateWithoutVendorInput = {
  id?: string
  bankName: string
  accountNumber: string
  accountHolder: string
  ifscCode: string
  cancelledChequeUrl: string
}

export type VendorBankAccountUncheckedCreateWithoutVendorInput = {
  id?: string
  bankName: string
  accountNumber: string
  accountHolder: string
  ifscCode: string
  cancelledChequeUrl: string
}

export type VendorBankAccountCreateOrConnectWithoutVendorInput = {
  where: Prisma.VendorBankAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.VendorBankAccountCreateWithoutVendorInput, Prisma.VendorBankAccountUncheckedCreateWithoutVendorInput>
}

export type VendorBankAccountUpsertWithoutVendorInput = {
  update: Prisma.XOR<Prisma.VendorBankAccountUpdateWithoutVendorInput, Prisma.VendorBankAccountUncheckedUpdateWithoutVendorInput>
  create: Prisma.XOR<Prisma.VendorBankAccountCreateWithoutVendorInput, Prisma.VendorBankAccountUncheckedCreateWithoutVendorInput>
  where?: Prisma.VendorBankAccountWhereInput
}

export type VendorBankAccountUpdateToOneWithWhereWithoutVendorInput = {
  where?: Prisma.VendorBankAccountWhereInput
  data: Prisma.XOR<Prisma.VendorBankAccountUpdateWithoutVendorInput, Prisma.VendorBankAccountUncheckedUpdateWithoutVendorInput>
}

export type VendorBankAccountUpdateWithoutVendorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  accountHolder?: Prisma.StringFieldUpdateOperationsInput | string
  ifscCode?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledChequeUrl?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VendorBankAccountUncheckedUpdateWithoutVendorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.StringFieldUpdateOperationsInput | string
  accountHolder?: Prisma.StringFieldUpdateOperationsInput | string
  ifscCode?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledChequeUrl?: Prisma.StringFieldUpdateOperationsInput | string
}



export type VendorBankAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vendorId?: boolean
  bankName?: boolean
  accountNumber?: boolean
  accountHolder?: boolean
  ifscCode?: boolean
  cancelledChequeUrl?: boolean
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendorBankAccount"]>

export type VendorBankAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vendorId?: boolean
  bankName?: boolean
  accountNumber?: boolean
  accountHolder?: boolean
  ifscCode?: boolean
  cancelledChequeUrl?: boolean
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendorBankAccount"]>

export type VendorBankAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vendorId?: boolean
  bankName?: boolean
  accountNumber?: boolean
  accountHolder?: boolean
  ifscCode?: boolean
  cancelledChequeUrl?: boolean
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendorBankAccount"]>

export type VendorBankAccountSelectScalar = {
  id?: boolean
  vendorId?: boolean
  bankName?: boolean
  accountNumber?: boolean
  accountHolder?: boolean
  ifscCode?: boolean
  cancelledChequeUrl?: boolean
}

export type VendorBankAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "vendorId" | "bankName" | "accountNumber" | "accountHolder" | "ifscCode" | "cancelledChequeUrl", ExtArgs["result"]["vendorBankAccount"]>
export type VendorBankAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}
export type VendorBankAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}
export type VendorBankAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}

export type $VendorBankAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VendorBankAccount"
  objects: {
    vendor: Prisma.$VendorPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    vendorId: string
    bankName: string
    accountNumber: string
    accountHolder: string
    ifscCode: string
    cancelledChequeUrl: string
  }, ExtArgs["result"]["vendorBankAccount"]>
  composites: {}
}

export type VendorBankAccountGetPayload<S extends boolean | null | undefined | VendorBankAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload, S>

export type VendorBankAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VendorBankAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VendorBankAccountCountAggregateInputType | true
  }

export interface VendorBankAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VendorBankAccount'], meta: { name: 'VendorBankAccount' } }
  /**
   * Find zero or one VendorBankAccount that matches the filter.
   * @param {VendorBankAccountFindUniqueArgs} args - Arguments to find a VendorBankAccount
   * @example
   * // Get one VendorBankAccount
   * const vendorBankAccount = await prisma.vendorBankAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VendorBankAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, VendorBankAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VendorBankAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VendorBankAccountFindUniqueOrThrowArgs} args - Arguments to find a VendorBankAccount
   * @example
   * // Get one VendorBankAccount
   * const vendorBankAccount = await prisma.vendorBankAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VendorBankAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VendorBankAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VendorBankAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountFindFirstArgs} args - Arguments to find a VendorBankAccount
   * @example
   * // Get one VendorBankAccount
   * const vendorBankAccount = await prisma.vendorBankAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VendorBankAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, VendorBankAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VendorBankAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountFindFirstOrThrowArgs} args - Arguments to find a VendorBankAccount
   * @example
   * // Get one VendorBankAccount
   * const vendorBankAccount = await prisma.vendorBankAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VendorBankAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VendorBankAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VendorBankAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VendorBankAccounts
   * const vendorBankAccounts = await prisma.vendorBankAccount.findMany()
   * 
   * // Get first 10 VendorBankAccounts
   * const vendorBankAccounts = await prisma.vendorBankAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vendorBankAccountWithIdOnly = await prisma.vendorBankAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VendorBankAccountFindManyArgs>(args?: Prisma.SelectSubset<T, VendorBankAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VendorBankAccount.
   * @param {VendorBankAccountCreateArgs} args - Arguments to create a VendorBankAccount.
   * @example
   * // Create one VendorBankAccount
   * const VendorBankAccount = await prisma.vendorBankAccount.create({
   *   data: {
   *     // ... data to create a VendorBankAccount
   *   }
   * })
   * 
   */
  create<T extends VendorBankAccountCreateArgs>(args: Prisma.SelectSubset<T, VendorBankAccountCreateArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VendorBankAccounts.
   * @param {VendorBankAccountCreateManyArgs} args - Arguments to create many VendorBankAccounts.
   * @example
   * // Create many VendorBankAccounts
   * const vendorBankAccount = await prisma.vendorBankAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VendorBankAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, VendorBankAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VendorBankAccounts and returns the data saved in the database.
   * @param {VendorBankAccountCreateManyAndReturnArgs} args - Arguments to create many VendorBankAccounts.
   * @example
   * // Create many VendorBankAccounts
   * const vendorBankAccount = await prisma.vendorBankAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VendorBankAccounts and only return the `id`
   * const vendorBankAccountWithIdOnly = await prisma.vendorBankAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VendorBankAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VendorBankAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VendorBankAccount.
   * @param {VendorBankAccountDeleteArgs} args - Arguments to delete one VendorBankAccount.
   * @example
   * // Delete one VendorBankAccount
   * const VendorBankAccount = await prisma.vendorBankAccount.delete({
   *   where: {
   *     // ... filter to delete one VendorBankAccount
   *   }
   * })
   * 
   */
  delete<T extends VendorBankAccountDeleteArgs>(args: Prisma.SelectSubset<T, VendorBankAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VendorBankAccount.
   * @param {VendorBankAccountUpdateArgs} args - Arguments to update one VendorBankAccount.
   * @example
   * // Update one VendorBankAccount
   * const vendorBankAccount = await prisma.vendorBankAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VendorBankAccountUpdateArgs>(args: Prisma.SelectSubset<T, VendorBankAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VendorBankAccounts.
   * @param {VendorBankAccountDeleteManyArgs} args - Arguments to filter VendorBankAccounts to delete.
   * @example
   * // Delete a few VendorBankAccounts
   * const { count } = await prisma.vendorBankAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VendorBankAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, VendorBankAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VendorBankAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VendorBankAccounts
   * const vendorBankAccount = await prisma.vendorBankAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VendorBankAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, VendorBankAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VendorBankAccounts and returns the data updated in the database.
   * @param {VendorBankAccountUpdateManyAndReturnArgs} args - Arguments to update many VendorBankAccounts.
   * @example
   * // Update many VendorBankAccounts
   * const vendorBankAccount = await prisma.vendorBankAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VendorBankAccounts and only return the `id`
   * const vendorBankAccountWithIdOnly = await prisma.vendorBankAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VendorBankAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VendorBankAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VendorBankAccount.
   * @param {VendorBankAccountUpsertArgs} args - Arguments to update or create a VendorBankAccount.
   * @example
   * // Update or create a VendorBankAccount
   * const vendorBankAccount = await prisma.vendorBankAccount.upsert({
   *   create: {
   *     // ... data to create a VendorBankAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VendorBankAccount we want to update
   *   }
   * })
   */
  upsert<T extends VendorBankAccountUpsertArgs>(args: Prisma.SelectSubset<T, VendorBankAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__VendorBankAccountClient<runtime.Types.Result.GetResult<Prisma.$VendorBankAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VendorBankAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountCountArgs} args - Arguments to filter VendorBankAccounts to count.
   * @example
   * // Count the number of VendorBankAccounts
   * const count = await prisma.vendorBankAccount.count({
   *   where: {
   *     // ... the filter for the VendorBankAccounts we want to count
   *   }
   * })
  **/
  count<T extends VendorBankAccountCountArgs>(
    args?: Prisma.Subset<T, VendorBankAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VendorBankAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VendorBankAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VendorBankAccountAggregateArgs>(args: Prisma.Subset<T, VendorBankAccountAggregateArgs>): Prisma.PrismaPromise<GetVendorBankAccountAggregateType<T>>

  /**
   * Group by VendorBankAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorBankAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VendorBankAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VendorBankAccountGroupByArgs['orderBy'] }
      : { orderBy?: VendorBankAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VendorBankAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVendorBankAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VendorBankAccount model
 */
readonly fields: VendorBankAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VendorBankAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VendorBankAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  vendor<T extends Prisma.VendorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VendorDefaultArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VendorBankAccount model
 */
export interface VendorBankAccountFieldRefs {
  readonly id: Prisma.FieldRef<"VendorBankAccount", 'String'>
  readonly vendorId: Prisma.FieldRef<"VendorBankAccount", 'String'>
  readonly bankName: Prisma.FieldRef<"VendorBankAccount", 'String'>
  readonly accountNumber: Prisma.FieldRef<"VendorBankAccount", 'String'>
  readonly accountHolder: Prisma.FieldRef<"VendorBankAccount", 'String'>
  readonly ifscCode: Prisma.FieldRef<"VendorBankAccount", 'String'>
  readonly cancelledChequeUrl: Prisma.FieldRef<"VendorBankAccount", 'String'>
}
    

// Custom InputTypes
/**
 * VendorBankAccount findUnique
 */
export type VendorBankAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which VendorBankAccount to fetch.
   */
  where: Prisma.VendorBankAccountWhereUniqueInput
}

/**
 * VendorBankAccount findUniqueOrThrow
 */
export type VendorBankAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which VendorBankAccount to fetch.
   */
  where: Prisma.VendorBankAccountWhereUniqueInput
}

/**
 * VendorBankAccount findFirst
 */
export type VendorBankAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which VendorBankAccount to fetch.
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VendorBankAccounts to fetch.
   */
  orderBy?: Prisma.VendorBankAccountOrderByWithRelationInput | Prisma.VendorBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VendorBankAccounts.
   */
  cursor?: Prisma.VendorBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VendorBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VendorBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VendorBankAccounts.
   */
  distinct?: Prisma.VendorBankAccountScalarFieldEnum | Prisma.VendorBankAccountScalarFieldEnum[]
}

/**
 * VendorBankAccount findFirstOrThrow
 */
export type VendorBankAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which VendorBankAccount to fetch.
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VendorBankAccounts to fetch.
   */
  orderBy?: Prisma.VendorBankAccountOrderByWithRelationInput | Prisma.VendorBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VendorBankAccounts.
   */
  cursor?: Prisma.VendorBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VendorBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VendorBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VendorBankAccounts.
   */
  distinct?: Prisma.VendorBankAccountScalarFieldEnum | Prisma.VendorBankAccountScalarFieldEnum[]
}

/**
 * VendorBankAccount findMany
 */
export type VendorBankAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which VendorBankAccounts to fetch.
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VendorBankAccounts to fetch.
   */
  orderBy?: Prisma.VendorBankAccountOrderByWithRelationInput | Prisma.VendorBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VendorBankAccounts.
   */
  cursor?: Prisma.VendorBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VendorBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VendorBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VendorBankAccounts.
   */
  distinct?: Prisma.VendorBankAccountScalarFieldEnum | Prisma.VendorBankAccountScalarFieldEnum[]
}

/**
 * VendorBankAccount create
 */
export type VendorBankAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a VendorBankAccount.
   */
  data: Prisma.XOR<Prisma.VendorBankAccountCreateInput, Prisma.VendorBankAccountUncheckedCreateInput>
}

/**
 * VendorBankAccount createMany
 */
export type VendorBankAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VendorBankAccounts.
   */
  data: Prisma.VendorBankAccountCreateManyInput | Prisma.VendorBankAccountCreateManyInput[]
}

/**
 * VendorBankAccount createManyAndReturn
 */
export type VendorBankAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * The data used to create many VendorBankAccounts.
   */
  data: Prisma.VendorBankAccountCreateManyInput | Prisma.VendorBankAccountCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VendorBankAccount update
 */
export type VendorBankAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a VendorBankAccount.
   */
  data: Prisma.XOR<Prisma.VendorBankAccountUpdateInput, Prisma.VendorBankAccountUncheckedUpdateInput>
  /**
   * Choose, which VendorBankAccount to update.
   */
  where: Prisma.VendorBankAccountWhereUniqueInput
}

/**
 * VendorBankAccount updateMany
 */
export type VendorBankAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VendorBankAccounts.
   */
  data: Prisma.XOR<Prisma.VendorBankAccountUpdateManyMutationInput, Prisma.VendorBankAccountUncheckedUpdateManyInput>
  /**
   * Filter which VendorBankAccounts to update
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * Limit how many VendorBankAccounts to update.
   */
  limit?: number
}

/**
 * VendorBankAccount updateManyAndReturn
 */
export type VendorBankAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * The data used to update VendorBankAccounts.
   */
  data: Prisma.XOR<Prisma.VendorBankAccountUpdateManyMutationInput, Prisma.VendorBankAccountUncheckedUpdateManyInput>
  /**
   * Filter which VendorBankAccounts to update
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * Limit how many VendorBankAccounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VendorBankAccount upsert
 */
export type VendorBankAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the VendorBankAccount to update in case it exists.
   */
  where: Prisma.VendorBankAccountWhereUniqueInput
  /**
   * In case the VendorBankAccount found by the `where` argument doesn't exist, create a new VendorBankAccount with this data.
   */
  create: Prisma.XOR<Prisma.VendorBankAccountCreateInput, Prisma.VendorBankAccountUncheckedCreateInput>
  /**
   * In case the VendorBankAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VendorBankAccountUpdateInput, Prisma.VendorBankAccountUncheckedUpdateInput>
}

/**
 * VendorBankAccount delete
 */
export type VendorBankAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
  /**
   * Filter which VendorBankAccount to delete.
   */
  where: Prisma.VendorBankAccountWhereUniqueInput
}

/**
 * VendorBankAccount deleteMany
 */
export type VendorBankAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VendorBankAccounts to delete
   */
  where?: Prisma.VendorBankAccountWhereInput
  /**
   * Limit how many VendorBankAccounts to delete.
   */
  limit?: number
}

/**
 * VendorBankAccount without action
 */
export type VendorBankAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorBankAccount
   */
  select?: Prisma.VendorBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VendorBankAccount
   */
  omit?: Prisma.VendorBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VendorBankAccountInclude<ExtArgs> | null
}
