
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkflowComment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkflowComment
 * 
 */
export type WorkflowCommentModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkflowCommentPayload>

export type AggregateWorkflowComment = {
  _count: WorkflowCommentCountAggregateOutputType | null
  _min: WorkflowCommentMinAggregateOutputType | null
  _max: WorkflowCommentMaxAggregateOutputType | null
}

export type WorkflowCommentMinAggregateOutputType = {
  id: string | null
  workflowId: string | null
  department: string | null
  reviewerId: string | null
  status: string | null
  comments: string | null
  createdAt: Date | null
}

export type WorkflowCommentMaxAggregateOutputType = {
  id: string | null
  workflowId: string | null
  department: string | null
  reviewerId: string | null
  status: string | null
  comments: string | null
  createdAt: Date | null
}

export type WorkflowCommentCountAggregateOutputType = {
  id: number
  workflowId: number
  department: number
  reviewerId: number
  status: number
  comments: number
  createdAt: number
  _all: number
}


export type WorkflowCommentMinAggregateInputType = {
  id?: true
  workflowId?: true
  department?: true
  reviewerId?: true
  status?: true
  comments?: true
  createdAt?: true
}

export type WorkflowCommentMaxAggregateInputType = {
  id?: true
  workflowId?: true
  department?: true
  reviewerId?: true
  status?: true
  comments?: true
  createdAt?: true
}

export type WorkflowCommentCountAggregateInputType = {
  id?: true
  workflowId?: true
  department?: true
  reviewerId?: true
  status?: true
  comments?: true
  createdAt?: true
  _all?: true
}

export type WorkflowCommentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowComment to aggregate.
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowComments to fetch.
   */
  orderBy?: Prisma.WorkflowCommentOrderByWithRelationInput | Prisma.WorkflowCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkflowCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkflowComments
  **/
  _count?: true | WorkflowCommentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkflowCommentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkflowCommentMaxAggregateInputType
}

export type GetWorkflowCommentAggregateType<T extends WorkflowCommentAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkflowComment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkflowComment[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkflowComment[P]>
}




export type WorkflowCommentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowCommentWhereInput
  orderBy?: Prisma.WorkflowCommentOrderByWithAggregationInput | Prisma.WorkflowCommentOrderByWithAggregationInput[]
  by: Prisma.WorkflowCommentScalarFieldEnum[] | Prisma.WorkflowCommentScalarFieldEnum
  having?: Prisma.WorkflowCommentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkflowCommentCountAggregateInputType | true
  _min?: WorkflowCommentMinAggregateInputType
  _max?: WorkflowCommentMaxAggregateInputType
}

export type WorkflowCommentGroupByOutputType = {
  id: string
  workflowId: string
  department: string
  reviewerId: string | null
  status: string
  comments: string
  createdAt: Date
  _count: WorkflowCommentCountAggregateOutputType | null
  _min: WorkflowCommentMinAggregateOutputType | null
  _max: WorkflowCommentMaxAggregateOutputType | null
}

export type GetWorkflowCommentGroupByPayload<T extends WorkflowCommentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkflowCommentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkflowCommentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkflowCommentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkflowCommentGroupByOutputType[P]>
      }
    >
  >



export type WorkflowCommentWhereInput = {
  AND?: Prisma.WorkflowCommentWhereInput | Prisma.WorkflowCommentWhereInput[]
  OR?: Prisma.WorkflowCommentWhereInput[]
  NOT?: Prisma.WorkflowCommentWhereInput | Prisma.WorkflowCommentWhereInput[]
  id?: Prisma.StringFilter<"WorkflowComment"> | string
  workflowId?: Prisma.StringFilter<"WorkflowComment"> | string
  department?: Prisma.StringFilter<"WorkflowComment"> | string
  reviewerId?: Prisma.StringNullableFilter<"WorkflowComment"> | string | null
  status?: Prisma.StringFilter<"WorkflowComment"> | string
  comments?: Prisma.StringFilter<"WorkflowComment"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkflowComment"> | Date | string
  workflow?: Prisma.XOR<Prisma.ApprovalWorkflowScalarRelationFilter, Prisma.ApprovalWorkflowWhereInput>
}

export type WorkflowCommentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  reviewerId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  workflow?: Prisma.ApprovalWorkflowOrderByWithRelationInput
}

export type WorkflowCommentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkflowCommentWhereInput | Prisma.WorkflowCommentWhereInput[]
  OR?: Prisma.WorkflowCommentWhereInput[]
  NOT?: Prisma.WorkflowCommentWhereInput | Prisma.WorkflowCommentWhereInput[]
  workflowId?: Prisma.StringFilter<"WorkflowComment"> | string
  department?: Prisma.StringFilter<"WorkflowComment"> | string
  reviewerId?: Prisma.StringNullableFilter<"WorkflowComment"> | string | null
  status?: Prisma.StringFilter<"WorkflowComment"> | string
  comments?: Prisma.StringFilter<"WorkflowComment"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkflowComment"> | Date | string
  workflow?: Prisma.XOR<Prisma.ApprovalWorkflowScalarRelationFilter, Prisma.ApprovalWorkflowWhereInput>
}, "id">

export type WorkflowCommentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  reviewerId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.WorkflowCommentCountOrderByAggregateInput
  _max?: Prisma.WorkflowCommentMaxOrderByAggregateInput
  _min?: Prisma.WorkflowCommentMinOrderByAggregateInput
}

export type WorkflowCommentScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkflowCommentScalarWhereWithAggregatesInput | Prisma.WorkflowCommentScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkflowCommentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkflowCommentScalarWhereWithAggregatesInput | Prisma.WorkflowCommentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkflowComment"> | string
  workflowId?: Prisma.StringWithAggregatesFilter<"WorkflowComment"> | string
  department?: Prisma.StringWithAggregatesFilter<"WorkflowComment"> | string
  reviewerId?: Prisma.StringNullableWithAggregatesFilter<"WorkflowComment"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"WorkflowComment"> | string
  comments?: Prisma.StringWithAggregatesFilter<"WorkflowComment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkflowComment"> | Date | string
}

export type WorkflowCommentCreateInput = {
  id?: string
  department: string
  reviewerId?: string | null
  status: string
  comments: string
  createdAt?: Date | string
  workflow: Prisma.ApprovalWorkflowCreateNestedOneWithoutCommentsInput
}

export type WorkflowCommentUncheckedCreateInput = {
  id?: string
  workflowId: string
  department: string
  reviewerId?: string | null
  status: string
  comments: string
  createdAt?: Date | string
}

export type WorkflowCommentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workflow?: Prisma.ApprovalWorkflowUpdateOneRequiredWithoutCommentsNestedInput
}

export type WorkflowCommentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workflowId?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowCommentCreateManyInput = {
  id?: string
  workflowId: string
  department: string
  reviewerId?: string | null
  status: string
  comments: string
  createdAt?: Date | string
}

export type WorkflowCommentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowCommentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workflowId?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowCommentListRelationFilter = {
  every?: Prisma.WorkflowCommentWhereInput
  some?: Prisma.WorkflowCommentWhereInput
  none?: Prisma.WorkflowCommentWhereInput
}

export type WorkflowCommentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkflowCommentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  reviewerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkflowCommentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  reviewerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkflowCommentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  reviewerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkflowCommentCreateNestedManyWithoutWorkflowInput = {
  create?: Prisma.XOR<Prisma.WorkflowCommentCreateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowCommentCreateWithoutWorkflowInput[] | Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowCommentCreateManyWorkflowInputEnvelope
  connect?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
}

export type WorkflowCommentUncheckedCreateNestedManyWithoutWorkflowInput = {
  create?: Prisma.XOR<Prisma.WorkflowCommentCreateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowCommentCreateWithoutWorkflowInput[] | Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowCommentCreateManyWorkflowInputEnvelope
  connect?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
}

export type WorkflowCommentUpdateManyWithoutWorkflowNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowCommentCreateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowCommentCreateWithoutWorkflowInput[] | Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput[]
  upsert?: Prisma.WorkflowCommentUpsertWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowCommentUpsertWithWhereUniqueWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowCommentCreateManyWorkflowInputEnvelope
  set?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  disconnect?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  delete?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  connect?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  update?: Prisma.WorkflowCommentUpdateWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowCommentUpdateWithWhereUniqueWithoutWorkflowInput[]
  updateMany?: Prisma.WorkflowCommentUpdateManyWithWhereWithoutWorkflowInput | Prisma.WorkflowCommentUpdateManyWithWhereWithoutWorkflowInput[]
  deleteMany?: Prisma.WorkflowCommentScalarWhereInput | Prisma.WorkflowCommentScalarWhereInput[]
}

export type WorkflowCommentUncheckedUpdateManyWithoutWorkflowNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowCommentCreateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowCommentCreateWithoutWorkflowInput[] | Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowCommentCreateOrConnectWithoutWorkflowInput[]
  upsert?: Prisma.WorkflowCommentUpsertWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowCommentUpsertWithWhereUniqueWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowCommentCreateManyWorkflowInputEnvelope
  set?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  disconnect?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  delete?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  connect?: Prisma.WorkflowCommentWhereUniqueInput | Prisma.WorkflowCommentWhereUniqueInput[]
  update?: Prisma.WorkflowCommentUpdateWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowCommentUpdateWithWhereUniqueWithoutWorkflowInput[]
  updateMany?: Prisma.WorkflowCommentUpdateManyWithWhereWithoutWorkflowInput | Prisma.WorkflowCommentUpdateManyWithWhereWithoutWorkflowInput[]
  deleteMany?: Prisma.WorkflowCommentScalarWhereInput | Prisma.WorkflowCommentScalarWhereInput[]
}

export type WorkflowCommentCreateWithoutWorkflowInput = {
  id?: string
  department: string
  reviewerId?: string | null
  status: string
  comments: string
  createdAt?: Date | string
}

export type WorkflowCommentUncheckedCreateWithoutWorkflowInput = {
  id?: string
  department: string
  reviewerId?: string | null
  status: string
  comments: string
  createdAt?: Date | string
}

export type WorkflowCommentCreateOrConnectWithoutWorkflowInput = {
  where: Prisma.WorkflowCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkflowCommentCreateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput>
}

export type WorkflowCommentCreateManyWorkflowInputEnvelope = {
  data: Prisma.WorkflowCommentCreateManyWorkflowInput | Prisma.WorkflowCommentCreateManyWorkflowInput[]
}

export type WorkflowCommentUpsertWithWhereUniqueWithoutWorkflowInput = {
  where: Prisma.WorkflowCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkflowCommentUpdateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedUpdateWithoutWorkflowInput>
  create: Prisma.XOR<Prisma.WorkflowCommentCreateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedCreateWithoutWorkflowInput>
}

export type WorkflowCommentUpdateWithWhereUniqueWithoutWorkflowInput = {
  where: Prisma.WorkflowCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkflowCommentUpdateWithoutWorkflowInput, Prisma.WorkflowCommentUncheckedUpdateWithoutWorkflowInput>
}

export type WorkflowCommentUpdateManyWithWhereWithoutWorkflowInput = {
  where: Prisma.WorkflowCommentScalarWhereInput
  data: Prisma.XOR<Prisma.WorkflowCommentUpdateManyMutationInput, Prisma.WorkflowCommentUncheckedUpdateManyWithoutWorkflowInput>
}

export type WorkflowCommentScalarWhereInput = {
  AND?: Prisma.WorkflowCommentScalarWhereInput | Prisma.WorkflowCommentScalarWhereInput[]
  OR?: Prisma.WorkflowCommentScalarWhereInput[]
  NOT?: Prisma.WorkflowCommentScalarWhereInput | Prisma.WorkflowCommentScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkflowComment"> | string
  workflowId?: Prisma.StringFilter<"WorkflowComment"> | string
  department?: Prisma.StringFilter<"WorkflowComment"> | string
  reviewerId?: Prisma.StringNullableFilter<"WorkflowComment"> | string | null
  status?: Prisma.StringFilter<"WorkflowComment"> | string
  comments?: Prisma.StringFilter<"WorkflowComment"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkflowComment"> | Date | string
}

export type WorkflowCommentCreateManyWorkflowInput = {
  id?: string
  department: string
  reviewerId?: string | null
  status: string
  comments: string
  createdAt?: Date | string
}

export type WorkflowCommentUpdateWithoutWorkflowInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowCommentUncheckedUpdateWithoutWorkflowInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowCommentUncheckedUpdateManyWithoutWorkflowInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  reviewerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkflowCommentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workflowId?: boolean
  department?: boolean
  reviewerId?: boolean
  status?: boolean
  comments?: boolean
  createdAt?: boolean
  workflow?: boolean | Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowComment"]>

export type WorkflowCommentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workflowId?: boolean
  department?: boolean
  reviewerId?: boolean
  status?: boolean
  comments?: boolean
  createdAt?: boolean
  workflow?: boolean | Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowComment"]>

export type WorkflowCommentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workflowId?: boolean
  department?: boolean
  reviewerId?: boolean
  status?: boolean
  comments?: boolean
  createdAt?: boolean
  workflow?: boolean | Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowComment"]>

export type WorkflowCommentSelectScalar = {
  id?: boolean
  workflowId?: boolean
  department?: boolean
  reviewerId?: boolean
  status?: boolean
  comments?: boolean
  createdAt?: boolean
}

export type WorkflowCommentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workflowId" | "department" | "reviewerId" | "status" | "comments" | "createdAt", ExtArgs["result"]["workflowComment"]>
export type WorkflowCommentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workflow?: boolean | Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>
}
export type WorkflowCommentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workflow?: boolean | Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>
}
export type WorkflowCommentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workflow?: boolean | Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>
}

export type $WorkflowCommentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkflowComment"
  objects: {
    workflow: Prisma.$ApprovalWorkflowPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workflowId: string
    department: string
    reviewerId: string | null
    status: string
    comments: string
    createdAt: Date
  }, ExtArgs["result"]["workflowComment"]>
  composites: {}
}

export type WorkflowCommentGetPayload<S extends boolean | null | undefined | WorkflowCommentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload, S>

export type WorkflowCommentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkflowCommentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkflowCommentCountAggregateInputType | true
  }

export interface WorkflowCommentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkflowComment'], meta: { name: 'WorkflowComment' } }
  /**
   * Find zero or one WorkflowComment that matches the filter.
   * @param {WorkflowCommentFindUniqueArgs} args - Arguments to find a WorkflowComment
   * @example
   * // Get one WorkflowComment
   * const workflowComment = await prisma.workflowComment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkflowCommentFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkflowCommentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkflowComment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkflowCommentFindUniqueOrThrowArgs} args - Arguments to find a WorkflowComment
   * @example
   * // Get one WorkflowComment
   * const workflowComment = await prisma.workflowComment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkflowCommentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkflowCommentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowComment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentFindFirstArgs} args - Arguments to find a WorkflowComment
   * @example
   * // Get one WorkflowComment
   * const workflowComment = await prisma.workflowComment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkflowCommentFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkflowCommentFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowComment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentFindFirstOrThrowArgs} args - Arguments to find a WorkflowComment
   * @example
   * // Get one WorkflowComment
   * const workflowComment = await prisma.workflowComment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkflowCommentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkflowCommentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkflowComments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkflowComments
   * const workflowComments = await prisma.workflowComment.findMany()
   * 
   * // Get first 10 WorkflowComments
   * const workflowComments = await prisma.workflowComment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workflowCommentWithIdOnly = await prisma.workflowComment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkflowCommentFindManyArgs>(args?: Prisma.SelectSubset<T, WorkflowCommentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkflowComment.
   * @param {WorkflowCommentCreateArgs} args - Arguments to create a WorkflowComment.
   * @example
   * // Create one WorkflowComment
   * const WorkflowComment = await prisma.workflowComment.create({
   *   data: {
   *     // ... data to create a WorkflowComment
   *   }
   * })
   * 
   */
  create<T extends WorkflowCommentCreateArgs>(args: Prisma.SelectSubset<T, WorkflowCommentCreateArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkflowComments.
   * @param {WorkflowCommentCreateManyArgs} args - Arguments to create many WorkflowComments.
   * @example
   * // Create many WorkflowComments
   * const workflowComment = await prisma.workflowComment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkflowCommentCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkflowCommentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkflowComments and returns the data saved in the database.
   * @param {WorkflowCommentCreateManyAndReturnArgs} args - Arguments to create many WorkflowComments.
   * @example
   * // Create many WorkflowComments
   * const workflowComment = await prisma.workflowComment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkflowComments and only return the `id`
   * const workflowCommentWithIdOnly = await prisma.workflowComment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkflowCommentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkflowCommentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkflowComment.
   * @param {WorkflowCommentDeleteArgs} args - Arguments to delete one WorkflowComment.
   * @example
   * // Delete one WorkflowComment
   * const WorkflowComment = await prisma.workflowComment.delete({
   *   where: {
   *     // ... filter to delete one WorkflowComment
   *   }
   * })
   * 
   */
  delete<T extends WorkflowCommentDeleteArgs>(args: Prisma.SelectSubset<T, WorkflowCommentDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkflowComment.
   * @param {WorkflowCommentUpdateArgs} args - Arguments to update one WorkflowComment.
   * @example
   * // Update one WorkflowComment
   * const workflowComment = await prisma.workflowComment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkflowCommentUpdateArgs>(args: Prisma.SelectSubset<T, WorkflowCommentUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkflowComments.
   * @param {WorkflowCommentDeleteManyArgs} args - Arguments to filter WorkflowComments to delete.
   * @example
   * // Delete a few WorkflowComments
   * const { count } = await prisma.workflowComment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkflowCommentDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkflowCommentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkflowComments
   * const workflowComment = await prisma.workflowComment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkflowCommentUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkflowCommentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowComments and returns the data updated in the database.
   * @param {WorkflowCommentUpdateManyAndReturnArgs} args - Arguments to update many WorkflowComments.
   * @example
   * // Update many WorkflowComments
   * const workflowComment = await prisma.workflowComment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkflowComments and only return the `id`
   * const workflowCommentWithIdOnly = await prisma.workflowComment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkflowCommentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkflowCommentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkflowComment.
   * @param {WorkflowCommentUpsertArgs} args - Arguments to update or create a WorkflowComment.
   * @example
   * // Update or create a WorkflowComment
   * const workflowComment = await prisma.workflowComment.upsert({
   *   create: {
   *     // ... data to create a WorkflowComment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkflowComment we want to update
   *   }
   * })
   */
  upsert<T extends WorkflowCommentUpsertArgs>(args: Prisma.SelectSubset<T, WorkflowCommentUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkflowCommentClient<runtime.Types.Result.GetResult<Prisma.$WorkflowCommentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkflowComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentCountArgs} args - Arguments to filter WorkflowComments to count.
   * @example
   * // Count the number of WorkflowComments
   * const count = await prisma.workflowComment.count({
   *   where: {
   *     // ... the filter for the WorkflowComments we want to count
   *   }
   * })
  **/
  count<T extends WorkflowCommentCountArgs>(
    args?: Prisma.Subset<T, WorkflowCommentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkflowCommentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkflowComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkflowCommentAggregateArgs>(args: Prisma.Subset<T, WorkflowCommentAggregateArgs>): Prisma.PrismaPromise<GetWorkflowCommentAggregateType<T>>

  /**
   * Group by WorkflowComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCommentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkflowCommentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkflowCommentGroupByArgs['orderBy'] }
      : { orderBy?: WorkflowCommentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkflowCommentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkflowCommentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkflowComment model
 */
readonly fields: WorkflowCommentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkflowComment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkflowCommentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workflow<T extends Prisma.ApprovalWorkflowDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApprovalWorkflowDefaultArgs<ExtArgs>>): Prisma.Prisma__ApprovalWorkflowClient<runtime.Types.Result.GetResult<Prisma.$ApprovalWorkflowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkflowComment model
 */
export interface WorkflowCommentFieldRefs {
  readonly id: Prisma.FieldRef<"WorkflowComment", 'String'>
  readonly workflowId: Prisma.FieldRef<"WorkflowComment", 'String'>
  readonly department: Prisma.FieldRef<"WorkflowComment", 'String'>
  readonly reviewerId: Prisma.FieldRef<"WorkflowComment", 'String'>
  readonly status: Prisma.FieldRef<"WorkflowComment", 'String'>
  readonly comments: Prisma.FieldRef<"WorkflowComment", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorkflowComment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkflowComment findUnique
 */
export type WorkflowCommentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowComment to fetch.
   */
  where: Prisma.WorkflowCommentWhereUniqueInput
}

/**
 * WorkflowComment findUniqueOrThrow
 */
export type WorkflowCommentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowComment to fetch.
   */
  where: Prisma.WorkflowCommentWhereUniqueInput
}

/**
 * WorkflowComment findFirst
 */
export type WorkflowCommentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowComment to fetch.
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowComments to fetch.
   */
  orderBy?: Prisma.WorkflowCommentOrderByWithRelationInput | Prisma.WorkflowCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowComments.
   */
  cursor?: Prisma.WorkflowCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowComments.
   */
  distinct?: Prisma.WorkflowCommentScalarFieldEnum | Prisma.WorkflowCommentScalarFieldEnum[]
}

/**
 * WorkflowComment findFirstOrThrow
 */
export type WorkflowCommentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowComment to fetch.
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowComments to fetch.
   */
  orderBy?: Prisma.WorkflowCommentOrderByWithRelationInput | Prisma.WorkflowCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowComments.
   */
  cursor?: Prisma.WorkflowCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowComments.
   */
  distinct?: Prisma.WorkflowCommentScalarFieldEnum | Prisma.WorkflowCommentScalarFieldEnum[]
}

/**
 * WorkflowComment findMany
 */
export type WorkflowCommentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowComments to fetch.
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowComments to fetch.
   */
  orderBy?: Prisma.WorkflowCommentOrderByWithRelationInput | Prisma.WorkflowCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkflowComments.
   */
  cursor?: Prisma.WorkflowCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowComments.
   */
  distinct?: Prisma.WorkflowCommentScalarFieldEnum | Prisma.WorkflowCommentScalarFieldEnum[]
}

/**
 * WorkflowComment create
 */
export type WorkflowCommentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkflowComment.
   */
  data: Prisma.XOR<Prisma.WorkflowCommentCreateInput, Prisma.WorkflowCommentUncheckedCreateInput>
}

/**
 * WorkflowComment createMany
 */
export type WorkflowCommentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkflowComments.
   */
  data: Prisma.WorkflowCommentCreateManyInput | Prisma.WorkflowCommentCreateManyInput[]
}

/**
 * WorkflowComment createManyAndReturn
 */
export type WorkflowCommentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * The data used to create many WorkflowComments.
   */
  data: Prisma.WorkflowCommentCreateManyInput | Prisma.WorkflowCommentCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkflowComment update
 */
export type WorkflowCommentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkflowComment.
   */
  data: Prisma.XOR<Prisma.WorkflowCommentUpdateInput, Prisma.WorkflowCommentUncheckedUpdateInput>
  /**
   * Choose, which WorkflowComment to update.
   */
  where: Prisma.WorkflowCommentWhereUniqueInput
}

/**
 * WorkflowComment updateMany
 */
export type WorkflowCommentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkflowComments.
   */
  data: Prisma.XOR<Prisma.WorkflowCommentUpdateManyMutationInput, Prisma.WorkflowCommentUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowComments to update
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * Limit how many WorkflowComments to update.
   */
  limit?: number
}

/**
 * WorkflowComment updateManyAndReturn
 */
export type WorkflowCommentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * The data used to update WorkflowComments.
   */
  data: Prisma.XOR<Prisma.WorkflowCommentUpdateManyMutationInput, Prisma.WorkflowCommentUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowComments to update
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * Limit how many WorkflowComments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkflowComment upsert
 */
export type WorkflowCommentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkflowComment to update in case it exists.
   */
  where: Prisma.WorkflowCommentWhereUniqueInput
  /**
   * In case the WorkflowComment found by the `where` argument doesn't exist, create a new WorkflowComment with this data.
   */
  create: Prisma.XOR<Prisma.WorkflowCommentCreateInput, Prisma.WorkflowCommentUncheckedCreateInput>
  /**
   * In case the WorkflowComment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkflowCommentUpdateInput, Prisma.WorkflowCommentUncheckedUpdateInput>
}

/**
 * WorkflowComment delete
 */
export type WorkflowCommentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
  /**
   * Filter which WorkflowComment to delete.
   */
  where: Prisma.WorkflowCommentWhereUniqueInput
}

/**
 * WorkflowComment deleteMany
 */
export type WorkflowCommentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowComments to delete
   */
  where?: Prisma.WorkflowCommentWhereInput
  /**
   * Limit how many WorkflowComments to delete.
   */
  limit?: number
}

/**
 * WorkflowComment without action
 */
export type WorkflowCommentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowComment
   */
  select?: Prisma.WorkflowCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowComment
   */
  omit?: Prisma.WorkflowCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowCommentInclude<ExtArgs> | null
}
