
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Role: 'Role',
  State: 'State',
  District: 'District',
  Category: 'Category',
  Product: 'Product',
  ProductVariant: 'ProductVariant',
  ProductImage: 'ProductImage',
  CulturalStory: 'CulturalStory',
  CartItem: 'CartItem',
  WishlistItem: 'WishlistItem',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Payment: 'Payment',
  Address: 'Address',
  Coupon: 'Coupon',
  Banner: 'Banner',
  Review: 'Review',
  BlogPost: 'BlogPost',
  Vendor: 'Vendor',
  VendorDocument: 'VendorDocument',
  VendorBankAccount: 'VendorBankAccount',
  ApprovalWorkflow: 'ApprovalWorkflow',
  WorkflowComment: 'WorkflowComment',
  ProductStatusHistory: 'ProductStatusHistory',
  Payout: 'Payout',
  StateMapAsset: 'StateMapAsset',
  FooterSection: 'FooterSection',
  FooterLink: 'FooterLink',
  FooterSocialLink: 'FooterSocialLink',
  FooterPaymentMethod: 'FooterPaymentMethod',
  FooterShippingPartner: 'FooterShippingPartner',
  FooterCertification: 'FooterCertification',
  FooterContactInfo: 'FooterContactInfo',
  FooterLanguage: 'FooterLanguage',
  FooterCurrency: 'FooterCurrency',
  FooterNewsletter: 'FooterNewsletter',
  FooterSettings: 'FooterSettings'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  passwordHash: 'passwordHash',
  roleId: 'roleId',
  isSuspended: 'isSuspended',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  permissions: 'permissions'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const StateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  isActive: 'isActive'
} as const

export type StateScalarFieldEnum = (typeof StateScalarFieldEnum)[keyof typeof StateScalarFieldEnum]


export const DistrictScalarFieldEnum = {
  id: 'id',
  stateId: 'stateId',
  name: 'name',
  odopProduct: 'odopProduct',
  isActive: 'isActive'
} as const

export type DistrictScalarFieldEnum = (typeof DistrictScalarFieldEnum)[keyof typeof DistrictScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  image: 'image',
  isActive: 'isActive'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  price: 'price',
  compareAtPrice: 'compareAtPrice',
  taxRate: 'taxRate',
  stock: 'stock',
  sku: 'sku',
  barcode: 'barcode',
  categoryId: 'categoryId',
  districtId: 'districtId',
  isFeatured: 'isFeatured',
  isTrending: 'isTrending',
  isNew: 'isNew',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  vendorId: 'vendorId'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  value: 'value',
  priceAdjustment: 'priceAdjustment',
  stock: 'stock'
} as const

export type ProductVariantScalarFieldEnum = (typeof ProductVariantScalarFieldEnum)[keyof typeof ProductVariantScalarFieldEnum]


export const ProductImageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url'
} as const

export type ProductImageScalarFieldEnum = (typeof ProductImageScalarFieldEnum)[keyof typeof ProductImageScalarFieldEnum]


export const CulturalStoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  artisanName: 'artisanName',
  artisanLocation: 'artisanLocation',
  artisanImage: 'artisanImage',
  history: 'history',
  culturalSignificance: 'culturalSignificance',
  productionMethod: 'productionMethod',
  geographicalIdentity: 'geographicalIdentity',
  awards: 'awards'
} as const

export type CulturalStoryScalarFieldEnum = (typeof CulturalStoryScalarFieldEnum)[keyof typeof CulturalStoryScalarFieldEnum]


export const CartItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  variantId: 'variantId',
  quantity: 'quantity'
} as const

export type CartItemScalarFieldEnum = (typeof CartItemScalarFieldEnum)[keyof typeof CartItemScalarFieldEnum]


export const WishlistItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId'
} as const

export type WishlistItemScalarFieldEnum = (typeof WishlistItemScalarFieldEnum)[keyof typeof WishlistItemScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  totalAmount: 'totalAmount',
  taxAmount: 'taxAmount',
  discountAmount: 'discountAmount',
  shippingAmount: 'shippingAmount',
  netAmount: 'netAmount',
  status: 'status',
  shippingAddressId: 'shippingAddressId',
  invoiceNumber: 'invoiceNumber',
  trackingId: 'trackingId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  vendorId: 'vendorId'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  quantity: 'quantity',
  price: 'price',
  taxRate: 'taxRate'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  gateway: 'gateway',
  transactionId: 'transactionId',
  status: 'status',
  amount: 'amount',
  createdAt: 'createdAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const AddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  street: 'street',
  city: 'city',
  state: 'state',
  pincode: 'pincode',
  country: 'country',
  isDefault: 'isDefault'
} as const

export type AddressScalarFieldEnum = (typeof AddressScalarFieldEnum)[keyof typeof AddressScalarFieldEnum]


export const CouponScalarFieldEnum = {
  id: 'id',
  code: 'code',
  type: 'type',
  value: 'value',
  minOrderAmount: 'minOrderAmount',
  maxDiscount: 'maxDiscount',
  startDate: 'startDate',
  endDate: 'endDate',
  usageLimit: 'usageLimit',
  usedCount: 'usedCount',
  isActive: 'isActive'
} as const

export type CouponScalarFieldEnum = (typeof CouponScalarFieldEnum)[keyof typeof CouponScalarFieldEnum]


export const BannerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  imageUrl: 'imageUrl',
  linkUrl: 'linkUrl',
  position: 'position',
  isActive: 'isActive'
} as const

export type BannerScalarFieldEnum = (typeof BannerScalarFieldEnum)[keyof typeof BannerScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  rating: 'rating',
  comment: 'comment',
  isApproved: 'isApproved',
  sentiment: 'sentiment',
  createdAt: 'createdAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const BlogPostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  content: 'content',
  summary: 'summary',
  image: 'image',
  author: 'author',
  isPublished: 'isPublished',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BlogPostScalarFieldEnum = (typeof BlogPostScalarFieldEnum)[keyof typeof BlogPostScalarFieldEnum]


export const VendorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  businessName: 'businessName',
  ownerName: 'ownerName',
  gstNumber: 'gstNumber',
  panNumber: 'panNumber',
  aadhaarNumber: 'aadhaarNumber',
  businessType: 'businessType',
  status: 'status',
  address: 'address',
  state: 'state',
  district: 'district',
  pinCode: 'pinCode',
  msmeCertificate: 'msmeCertificate',
  fssaiLicense: 'fssaiLicense',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VendorScalarFieldEnum = (typeof VendorScalarFieldEnum)[keyof typeof VendorScalarFieldEnum]


export const VendorDocumentScalarFieldEnum = {
  id: 'id',
  vendorId: 'vendorId',
  docType: 'docType',
  fileUrl: 'fileUrl',
  verifiedAt: 'verifiedAt',
  verifiedBy: 'verifiedBy',
  status: 'status'
} as const

export type VendorDocumentScalarFieldEnum = (typeof VendorDocumentScalarFieldEnum)[keyof typeof VendorDocumentScalarFieldEnum]


export const VendorBankAccountScalarFieldEnum = {
  id: 'id',
  vendorId: 'vendorId',
  bankName: 'bankName',
  accountNumber: 'accountNumber',
  accountHolder: 'accountHolder',
  ifscCode: 'ifscCode',
  cancelledChequeUrl: 'cancelledChequeUrl'
} as const

export type VendorBankAccountScalarFieldEnum = (typeof VendorBankAccountScalarFieldEnum)[keyof typeof VendorBankAccountScalarFieldEnum]


export const ApprovalWorkflowScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  currentStage: 'currentStage',
  assignedTo: 'assignedTo',
  updatedAt: 'updatedAt'
} as const

export type ApprovalWorkflowScalarFieldEnum = (typeof ApprovalWorkflowScalarFieldEnum)[keyof typeof ApprovalWorkflowScalarFieldEnum]


export const WorkflowCommentScalarFieldEnum = {
  id: 'id',
  workflowId: 'workflowId',
  department: 'department',
  reviewerId: 'reviewerId',
  status: 'status',
  comments: 'comments',
  createdAt: 'createdAt'
} as const

export type WorkflowCommentScalarFieldEnum = (typeof WorkflowCommentScalarFieldEnum)[keyof typeof WorkflowCommentScalarFieldEnum]


export const ProductStatusHistoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  changedBy: 'changedBy',
  remarks: 'remarks',
  createdAt: 'createdAt'
} as const

export type ProductStatusHistoryScalarFieldEnum = (typeof ProductStatusHistoryScalarFieldEnum)[keyof typeof ProductStatusHistoryScalarFieldEnum]


export const PayoutScalarFieldEnum = {
  id: 'id',
  vendorId: 'vendorId',
  orderId: 'orderId',
  netEarnings: 'netEarnings',
  commissionDeducted: 'commissionDeducted',
  tdsDeducted: 'tdsDeducted',
  gstCollected: 'gstCollected',
  payoutStatus: 'payoutStatus',
  settledAt: 'settledAt'
} as const

export type PayoutScalarFieldEnum = (typeof PayoutScalarFieldEnum)[keyof typeof PayoutScalarFieldEnum]


export const StateMapAssetScalarFieldEnum = {
  id: 'id',
  stateName: 'stateName',
  stateCode: 'stateCode',
  imageUrl: 'imageUrl',
  imageType: 'imageType',
  fileSize: 'fileSize',
  width: 'width',
  height: 'height',
  version: 'version',
  uploadedBy: 'uploadedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status'
} as const

export type StateMapAssetScalarFieldEnum = (typeof StateMapAssetScalarFieldEnum)[keyof typeof StateMapAssetScalarFieldEnum]


export const FooterSectionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  isEnabled: 'isEnabled',
  order: 'order'
} as const

export type FooterSectionScalarFieldEnum = (typeof FooterSectionScalarFieldEnum)[keyof typeof FooterSectionScalarFieldEnum]


export const FooterLinkScalarFieldEnum = {
  id: 'id',
  sectionId: 'sectionId',
  label: 'label',
  url: 'url',
  order: 'order',
  isEnabled: 'isEnabled'
} as const

export type FooterLinkScalarFieldEnum = (typeof FooterLinkScalarFieldEnum)[keyof typeof FooterLinkScalarFieldEnum]


export const FooterSocialLinkScalarFieldEnum = {
  id: 'id',
  platform: 'platform',
  url: 'url',
  iconText: 'iconText',
  isEnabled: 'isEnabled'
} as const

export type FooterSocialLinkScalarFieldEnum = (typeof FooterSocialLinkScalarFieldEnum)[keyof typeof FooterSocialLinkScalarFieldEnum]


export const FooterPaymentMethodScalarFieldEnum = {
  id: 'id',
  name: 'name',
  imageUrl: 'imageUrl',
  isEnabled: 'isEnabled'
} as const

export type FooterPaymentMethodScalarFieldEnum = (typeof FooterPaymentMethodScalarFieldEnum)[keyof typeof FooterPaymentMethodScalarFieldEnum]


export const FooterShippingPartnerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  imageUrl: 'imageUrl',
  isEnabled: 'isEnabled'
} as const

export type FooterShippingPartnerScalarFieldEnum = (typeof FooterShippingPartnerScalarFieldEnum)[keyof typeof FooterShippingPartnerScalarFieldEnum]


export const FooterCertificationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  imageUrl: 'imageUrl',
  isEnabled: 'isEnabled'
} as const

export type FooterCertificationScalarFieldEnum = (typeof FooterCertificationScalarFieldEnum)[keyof typeof FooterCertificationScalarFieldEnum]


export const FooterContactInfoScalarFieldEnum = {
  id: 'id',
  corporateOffice: 'corporateOffice',
  registeredOffice: 'registeredOffice',
  email: 'email',
  phone: 'phone',
  whatsApp: 'whatsApp',
  businessHours: 'businessHours',
  googleMapsUrl: 'googleMapsUrl'
} as const

export type FooterContactInfoScalarFieldEnum = (typeof FooterContactInfoScalarFieldEnum)[keyof typeof FooterContactInfoScalarFieldEnum]


export const FooterLanguageScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  isEnabled: 'isEnabled'
} as const

export type FooterLanguageScalarFieldEnum = (typeof FooterLanguageScalarFieldEnum)[keyof typeof FooterLanguageScalarFieldEnum]


export const FooterCurrencyScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  symbol: 'symbol',
  isEnabled: 'isEnabled'
} as const

export type FooterCurrencyScalarFieldEnum = (typeof FooterCurrencyScalarFieldEnum)[keyof typeof FooterCurrencyScalarFieldEnum]


export const FooterNewsletterScalarFieldEnum = {
  id: 'id',
  email: 'email',
  createdAt: 'createdAt'
} as const

export type FooterNewsletterScalarFieldEnum = (typeof FooterNewsletterScalarFieldEnum)[keyof typeof FooterNewsletterScalarFieldEnum]


export const FooterSettingsScalarFieldEnum = {
  id: 'id',
  copyright: 'copyright',
  companyRegistration: 'companyRegistration',
  gstNumber: 'gstNumber',
  trademark: 'trademark',
  accessibilityStmt: 'accessibilityStmt',
  cookieSettings: 'cookieSettings',
  versionNumber: 'versionNumber'
} as const

export type FooterSettingsScalarFieldEnum = (typeof FooterSettingsScalarFieldEnum)[keyof typeof FooterSettingsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

